#!/bin/bash
# build.sh - Aggregates JS modules into the production script

clear

OUTPUT="web/frontend/script.js"

# Create the output file and clear previous contents
echo "/** Auto-generated by build.sh **/" > $OUTPUT

# Append files in order of dependency
cat web/frontend/js/app.js \
    web/frontend/js/app_spinner.js \
    web/frontend/js/app_modal.js \
    web/frontend/js/tiktok_controller.js \
    web/frontend/js/agent_controller.js \
    web/frontend/js/agentic_controller.js \
    web/frontend/js/controllers.js \
    web/frontend/js/job_progress_controller.js \
    web/frontend/js/health_controller.js \
    web/frontend/js/snapshots_controller.js \
    web/frontend/js/pentest_controller.js \
    web/frontend/js/page_registry.js \
    web/frontend/js/mobile_controller.js \
    web/frontend/js/model.js \
    web/frontend/js/view.js >> $OUTPUT

echo "Successfully built $OUTPUT"


OUTPUT="web/frontend/bootstrap-lite.css"

# Create the output file and clear previous contents
echo "/** Auto-generated by build.sh **/" > $OUTPUT

# Append files in order of dependency
cat web/frontend/css/app.css \
    web/frontend/css/agents.css \
    web/frontend/css/agentic.css \
    web/frontend/css/home.css \
    web/frontend/css/health.css \
    web/frontend/css/tiktok.css \
    web/frontend/css/welcome.css \
    web/frontend/css/modal.css \
    web/frontend/css/spinner.css \
    web/frontend/css/preview.css \
    web/frontend/css/autoform.css \
    web/frontend/css/neural-pipeline.css \
    web/frontend/css/snapshots.css \
    web/frontend/css/pentest.css \
    web/frontend/css/mobile.css \
    web/frontend/css/screen-agent-detail.css \
    web/frontend/css/leads.css >> $OUTPUT

echo "Successfully built $OUTPUT"
