#!/bin/bash
# build.sh - Aggregates JS modules into the production script

OUTPUT="web/frontend/script.js"

# Create the output file and clear previous contents
echo "/** Auto-generated by build.sh **/" > $OUTPUT

# Append files in order of dependency
cat web/frontend/js/app.js \
    web/frontend/js/model.js \
    web/frontend/js/view.js \
    web/frontend/js/controller.js \
    web/frontend/js/home_controller.js \
    web/frontend/js/rag_controller.js \
    web/frontend/js/email_controller.js \
    web/frontend/js/agent_controller.js \
    web/frontend/js/registry.js \
    web/frontend/js/init.js >> $OUTPUT

echo "Successfully built $OUTPUT"
