#!/bin/bash
# build.sh - Aggregates JS modules into the production script

clear

OUTPUT="web/frontend/script.js"

# Create the output file and clear previous contents
echo "/** Auto-generated by build.sh **/" > $OUTPUT

# Append files in order of dependency
cat web/frontend/js/app.js \
    web/frontend/js/controllers.js \
    web/frontend/js/model.js \
    web/frontend/js/view.js >> $OUTPUT

echo "Successfully built $OUTPUT"


OUTPUT="web/frontend/bootstrap-lite.css"

# Create the output file and clear previous contents
echo "/** Auto-generated by build.sh **/" > $OUTPUT

# Append files in order of dependency
cat web/frontend/css/app.css \
    web/frontend/css/agents.css \
    web/frontend/css/tiktok.css \
    web/frontend/css/welcome.css >> $OUTPUT

echo "Successfully built $OUTPUT"
