#!/bin/bash
set -euo pipefail

# ===================== DEFAULT CONFIG & VARIABLES =====================

# Database Configuration
DB_HOST="localhost"
DB_USER="appuser"
DB_PASS="ChangeMeToAStrongPassword123!"
DB_NAME="myapp_db"
MYSQL_ROOT_PASS=""

# Web Server Configuration
DOMAIN="example.com"
WEB_ROOT="/var/www/myapp"
PHP_VERSION="8.3"

# Project Paths
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_PATH="${ROOT_DIR}"
STORAGE_PATH="${PROJECT_PATH}/storage"
VENV="${PROJECT_PATH}/venv"

CURRENT_USER="$(whoami)"

# ===================== PARSE ARGUMENTS =====================
while getopts ":H:u:p:d:r:D:w:v:" opt; do
  case "${opt}" in
    H) DB_HOST="${OPTARG}" ;;
    u) DB_USER="${OPTARG}" ;;
    p) DB_PASS="${OPTARG}" ;;
    d) DB_NAME="${OPTARG}" ;;
    r) MYSQL_ROOT_PASS="${OPTARG}" ;;
    D) DOMAIN="${OPTARG}" ;;
    w) WEB_ROOT="${OPTARG}" ;;
    v) PHP_VERSION="${OPTARG}" ;;
    \?) 
        echo "Usage: $0 [-H host] [-u user] [-p pass] [-d db] [-r rootpass] [-D domain] [-w webroot] [-v phpversion]"
        exit 1 
        ;;
  esac
done

# ===================== PRE-INSTALLATION CLEAN-UP =====================
echo -e "\n=== Pre-installation Cleanup ==="

if [ -f /etc/nginx/sites-available/default ]; then
    echo "Removing default Nginx site..."
    sudo rm -f /etc/nginx/sites-available/default
    sudo rm -f /etc/nginx/sites-enabled/default
    echo "✅ Default Nginx site removed."
fi

if [ -f "/etc/nginx/sites-available/${DOMAIN}" ]; then
    echo "Removing old configuration for ${DOMAIN}..."
    sudo rm -f "/etc/nginx/sites-available/${DOMAIN}"
    sudo rm -f "/etc/nginx/sites-enabled/${DOMAIN}"
    echo "✅ Old site configuration cleaned."
fi

# ===================== SYSTEM SETUP (LEMP + Python) =====================
echo -e "\n=== System Setup: Installing LEMP + Python ==="

echo "Updating package index..."
sudo apt-get update -qq

# Easy to edit package list
PACKAGES=(
    nginx
    mariadb-server
    php${PHP_VERSION}
    php${PHP_VERSION}-fpm
    php${PHP_VERSION}-mysql
    php${PHP_VERSION}-curl
    php${PHP_VERSION}-mbstring
    php${PHP_VERSION}-xml
    php${PHP_VERSION}-zip
    php${PHP_VERSION}-gd
    python3-venv
    python3-pip
    curl
)

echo "Installing packages..."
sudo apt-get install -y "${PACKAGES[@]}"

# Enable services
echo -e "\nEnabling services..."
for service in nginx mariadb "php${PHP_VERSION}-fpm"; do
    sudo systemctl enable "${service}" --now 2>/dev/null || echo "   ⚠️  Could not enable ${service}"
done

echo "✅ Core system setup completed."

# ===================== FIX PERMISSIONS =====================
echo -e "\n=== Fixing Storage Permissions ==="

mkdir -p "${STORAGE_PATH}"
sudo chown -R "${CURRENT_USER}:www-data" "${STORAGE_PATH}"
sudo chmod -R 2775 "${STORAGE_PATH}"
sudo find "${STORAGE_PATH}" -type d -exec chmod g+s {} +

echo "✅ Storage permissions applied (${CURRENT_USER}:www-data)"

# ===================== MYSQL SETUP =====================
echo -e "\n=== Configuring MariaDB ==="

if [ -n "$MYSQL_ROOT_PASS" ]; then
    MYSQL_CMD=(mysql -uroot -p"${MYSQL_ROOT_PASS}")
else
    MYSQL_CMD=(sudo mysql)
fi

"${MYSQL_CMD[@]}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${DB_USER}'@'${DB_HOST}' 
    IDENTIFIED BY '${DB_PASS}';

GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* 
    TO '${DB_USER}'@'${DB_HOST}';

FLUSH PRIVILEGES;
SQL

echo "✅ Database and user created."

# ===================== CREATE env.php =====================
echo -e "\n=== Creating env.php ==="

cat > env.php <<PHP_EOF
<?php
/**
 * Database Configuration - Generated by install.sh
 */

define('DB_HOST', '${DB_HOST}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
define('DB_NAME', '${DB_NAME}');

PHP_EOF

echo "✅ env.php created."

# ===================== SETUP WEB STORAGE STRUCTURE =====================
echo -e "\n=== Setting up Web Storage Structure (NATS-Lite) ==="

echo "📁 Creating storage directories..."

mkdir -p "${STORAGE_PATH}/logs" \
         "${STORAGE_PATH}/vectors" \
         "${STORAGE_PATH}/uploads/nats/ingest" \
         "${STORAGE_PATH}/uploads/nats/process" \
         "${STORAGE_PATH}/uploads/nats/archive" \
         "${STORAGE_PATH}/uploads/nats/fail"

# Create initial log files
touch "${STORAGE_PATH}/logs/laravel.log" \
      "${STORAGE_PATH}/logs/worker.log"

echo "✅ Storage directory structure created."

# Apply permissions
echo "Applying permissions..."
# (This will call the fix-permissions section we already have)
sudo chown -R "${CURRENT_USER}:www-data" "${STORAGE_PATH}"
sudo chmod -R 2775 "${STORAGE_PATH}"
sudo find "${STORAGE_PATH}" -type d -exec chmod g+s {} +

echo "✅ Storage structure and permissions verified."

# ===================== WEB ROOT & NGINX SETUP =====================
echo -e "\n=== Configuring Nginx ==="

sudo mkdir -p "${WEB_ROOT}"
sudo chown -R www-data:www-data "${WEB_ROOT}"
sudo chmod -R 755 "${WEB_ROOT}"

# Create Nginx config
sudo tee /etc/nginx/sites-available/${DOMAIN} > /dev/null <<NGINX_EOF
server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN};

    root ${WEB_ROOT};
    index index.php index.html index.htm;

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php${PHP_VERSION}-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
NGINX_EOF

sudo ln -sf /etc/nginx/sites-available/${DOMAIN} /etc/nginx/sites-enabled/
sudo nginx -t && sudo systemctl reload nginx

echo "✅ Nginx configured for ${DOMAIN}"

# ===================== SET HOSTS =====================
echo -e "\n=== Updating /etc/hosts ==="
HOSTS_ENTRY="127.0.0.1   ${DOMAIN} www.${DOMAIN}"
if ! grep -q "${DOMAIN}" /etc/hosts; then
    echo "${HOSTS_ENTRY}" | sudo tee -a /etc/hosts > /dev/null
    echo "✅ Added ${DOMAIN} to /etc/hosts"
else
    echo "ℹ️  ${DOMAIN} already in /etc/hosts"
fi

# ===================== SETUP PYTHON ENVIRONMENT =====================
echo -e "\n=== Setting up Python Virtual Environment ==="

if [ -d "${VENV}" ]; then
    echo "Virtual environment already exists at ${VENV}"
else
    echo "🐍 Creating virtual environment..."
    python3 -m venv "${VENV}"
    echo "✅ Virtual environment created."
fi

# Uncomment when ready to test Models
# echo "Upgrading pip..."
# "${PIP}" install --upgrade pip

# echo "Installing Python dependencies..."
# "${PIP}" install -r requirements.txt

# echo "🧠 Pre-loading Neural Model (all-MiniLM-L6-v2)..."
# # Pre-download and warm up the model (CPU only)
# "${PYTHON}" -c '
# from sentence_transformers import SentenceTransformer
# print("Loading model all-MiniLM-L6-v2...")
# model = SentenceTransformer("all-MiniLM-L6-v2", device="cpu")
# print("Model loaded successfully.")
# ' || echo "⚠️  Model pre-loading failed (will be downloaded on first use)."

# echo "✅ Python environment and model are ready."

# ===================== FINAL SUMMARY =====================
echo -e "\n========================================"
echo "Installation completed successfully!"
echo "========================================"
echo "Domain       : ${DOMAIN}"
echo "Web Root     : ${WEB_ROOT}"
echo "PHP Version  : ${PHP_VERSION}"
echo "Database     : ${DB_NAME}"
echo "Storage Path : ${STORAGE_PATH}"
echo "env.php      : Created"
echo ""
echo "Next steps:"
echo "   1. Upload your application files to ${WEB_ROOT}"
echo "   2. Change DB password in env.php"
echo "   3. Consider setting up SSL (Let's Encrypt)"
echo "========================================"