#!/bin/bash
set -euo pipefail

# ===================== DEFAULT CONFIG & VARIABLES =====================

# Database Configuration
DB_HOST="localhost"
DB_USER="sharpishly"
DB_PASS="sharpishly"
DB_NAME="sharpishly"
MYSQL_ROOT_PASS=""

# Web Server Configuration
DOMAIN="sharpishly.dev"
WEB_ROOT="/home/vboxuser/Documents/SHARPISHLY-THOMASONS/web/php/src"
PHP_VERSION="8.3"

# Project Paths
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_PATH="${ROOT_DIR}"
STORAGE_PATH="${PROJECT_PATH}/storage"
VENV="${PROJECT_PATH}/venv"

CURRENT_USER="$(whoami)"

# ===================== PARSE ARGUMENTS =====================
while getopts ":H:u:p:d:r:D:w:v:" opt; do
  case "${opt}" in
    H) DB_HOST="${OPTARG}" ;;
    u) DB_USER="${OPTARG}" ;;
    p) DB_PASS="${OPTARG}" ;;
    d) DB_NAME="${OPTARG}" ;;
    r) MYSQL_ROOT_PASS="${OPTARG}" ;;
    D) DOMAIN="${OPTARG}" ;;
    w) WEB_ROOT="${OPTARG}" ;;
    v) PHP_VERSION="${OPTARG}" ;;
    \?) 
        echo "Usage: $0 [-H host] [-u user] [-p pass] [-d db] [-r rootpass] [-D domain] [-w webroot] [-v phpversion]"
        exit 1 
        ;;
  esac
done

# ===================== PRE-INSTALLATION CLEAN-UP =====================
echo -e "\n=== Pre-installation Cleanup ==="

if [ -f /etc/nginx/sites-available/default ]; then
    echo "Removing default Nginx site..."
    sudo rm -f /etc/nginx/sites-available/default
    sudo rm -f /etc/nginx/sites-enabled/default
fi

if [ -f "/etc/nginx/sites-available/${DOMAIN}" ]; then
    echo "Removing old configuration for ${DOMAIN}..."
    sudo rm -f "/etc/nginx/sites-available/${DOMAIN}"
    sudo rm -f "/etc/nginx/sites-enabled/${DOMAIN}"
fi

# ===================== PHP REPOSITORY SETUP (SURY) =====================
echo -e "\n=== Setting up PHP ${PHP_VERSION} Repository (deb.sury.org) ==="

# Install dependencies
sudo apt-get install -y ca-certificates apt-transport-https lsb-release gnupg curl

echo "Adding official SURY PHP repository..."

# Download and install the official signing key
curl -fsSL https://packages.sury.org/php/apt.gpg | sudo gpg --dearmor -o /usr/share/keyrings/sury-php.gpg

# Add the repository
echo "deb [signed-by=/usr/share/keyrings/sury-php.gpg] https://packages.sury.org/php/ $(lsb_release -sc) main" | \
sudo tee /etc/apt/sources.list.d/sury-php.list > /dev/null

echo "✅ SURY PHP repository added successfully."

echo "Updating package list..."
sudo apt-get update -qq

# ===================== SYSTEM SETUP (LEMP + Python) =====================
echo -e "\n=== System Setup: Installing LEMP + Python ==="

# Easy to edit package list
PACKAGES=(
    nginx
    mariadb-server
    php${PHP_VERSION}
    php${PHP_VERSION}-fpm
    php${PHP_VERSION}-mysql
    php${PHP_VERSION}-curl
    php${PHP_VERSION}-mbstring
    php${PHP_VERSION}-xml
    php${PHP_VERSION}-zip
    php${PHP_VERSION}-gd
    python3-venv
    python3-pip
    curl
)

echo "Installing core packages..."
sudo apt-get install -y "${PACKAGES[@]}"

# Enable services
echo -e "\nEnabling services..."
for service in nginx mariadb "php${PHP_VERSION}-fpm"; do
    sudo systemctl enable "${service}" --now 2>/dev/null && \
    echo "   ✅ Enabled: ${service}" || \
    echo "   ⚠️  Could not enable ${service}"
done

echo "✅ Core system setup completed."

# ===================== FIX PERMISSIONS =====================
echo -e "\n=== Fixing Storage Permissions ==="

mkdir -p "${STORAGE_PATH}"
sudo chown -R "${CURRENT_USER}:www-data" "${STORAGE_PATH}"
sudo chmod -R 2775 "${STORAGE_PATH}"
sudo find "${STORAGE_PATH}" -type d -exec chmod g+s {} +

echo "✅ Storage permissions applied."

# ===================== MYSQL SETUP =====================
echo -e "\n=== Configuring MariaDB ==="

if [ -n "$MYSQL_ROOT_PASS" ]; then
    MYSQL_CMD=(mysql -uroot -p"${MYSQL_ROOT_PASS}")
else
    MYSQL_CMD=(sudo mysql)
fi

"${MYSQL_CMD[@]}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${DB_USER}'@'${DB_HOST}' 
    IDENTIFIED BY '${DB_PASS}';

GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* 
    TO '${DB_USER}'@'${DB_HOST}';

FLUSH PRIVILEGES;
SQL

echo "✅ Database and user created."

# ===================== CREATE env.php =====================
echo -e "\n=== Creating env.php ==="

cat > env.php <<PHP_EOF
<?php
/**
 * Database Configuration - Generated by install.sh
 */

define('DB_HOST', '${DB_HOST}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');
define('DB_NAME', '${DB_NAME}');

PHP_EOF

echo "✅ env.php created."

# ===================== SETUP WEB STORAGE STRUCTURE =====================
echo -e "\n=== Setting up Web Storage Structure ==="

mkdir -p "${STORAGE_PATH}"/{logs,vectors,uploads/nats/{ingest,process,archive,fail}}

touch "${STORAGE_PATH}/logs/laravel.log" \
      "${STORAGE_PATH}/logs/worker.log"

echo "✅ Storage structure created."

# ===================== WEB ROOT & NGINX SETUP =====================
echo -e "\n=== Configuring Nginx ==="

sudo mkdir -p "${WEB_ROOT}"
sudo chown -R www-data:www-data "${WEB_ROOT}"
sudo chmod -R 755 "${WEB_ROOT}"

sudo tee /etc/nginx/sites-available/${DOMAIN} > /dev/null <<NGINX_EOF
server {
    listen 80;
    server_name ${DOMAIN} www.${DOMAIN};

    root ${WEB_ROOT};
    index index.php index.html index.htm;

    # Logging - pointing to your local storage
    access_log /var/log/nginx/sharpishly_access.log;
    error_log  /var/log/nginx/sharpishly_error.log warn;

    # 1. Frontend SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # location ~ \.php$ {
    #     fastcgi_pass unix:/var/run/php/php${PHP_VERSION}-fpm.sock;
    #     fastcgi_index index.php;
    #     fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    #     include fastcgi_params;
    # }

    # 2. PHP API - Everything under /php or /api goes to index.php
    location ~ ^/(php|api)(/|$) {
        # Single entry point for all PHP routing
        fastcgi_param SCRIPT_FILENAME $base_path/web/php/src/index.php;
        fastcgi_param PATH_INFO       $fastcgi_path_info;

        include fastcgi_params;
        
        # NATIVE CHANGE: Connect to the local PHP-FPM socket instead of "php:9000"
        fastcgi_pass unix:/var/run/php/php${PHP_VERSION}-fpm.sock;

        # Preserve full original URI for router
        fastcgi_param REQUEST_URI      $request_uri;

        # Timeouts for Neural/Path B tasks
        fastcgi_read_timeout  600;
        fastcgi_send_timeout  600;

        # Buffering off for Path B streaming
        fastcgi_buffering     off;
    }

    # Security & Buffers
    client_max_body_size 50M;
    client_body_buffer_size 1M;
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options SAMEORIGIN;


    location ~ /\.ht {
        deny all;
    }
}
NGINX_EOF

sudo ln -sf /etc/nginx/sites-available/${DOMAIN} /etc/nginx/sites-enabled/
sudo nginx -t && sudo systemctl reload nginx

echo "✅ Nginx configured for ${DOMAIN}"

# ===================== SET HOSTS =====================
echo -e "\n=== Updating /etc/hosts ==="
HOSTS_ENTRY="127.0.0.1   ${DOMAIN} www.${DOMAIN}"
if ! grep -q "${DOMAIN}" /etc/hosts; then
    echo "${HOSTS_ENTRY}" | sudo tee -a /etc/hosts > /dev/null
    echo "✅ Added ${DOMAIN} to /etc/hosts"
else
    echo "ℹ️  ${DOMAIN} already in /etc/hosts"
fi

# ===================== FINAL SUMMARY =====================
echo -e "\n========================================"
echo "Installation completed successfully!"
echo "========================================"
echo "Domain       : ${DOMAIN}"
echo "Web Root     : ${WEB_ROOT}"
echo "PHP Version  : ${PHP_VERSION}"
echo "Database     : ${DB_NAME}"
echo "Storage Path : ${STORAGE_PATH}"
echo "env.php      : Created"
echo ""
echo "Next steps:"
echo "   1. Upload your application files to ${WEB_ROOT}"
echo "   2. Change DB password in env.php"
echo "   3. Consider setting up SSL (Let's Encrypt)"
echo "========================================"