/** Auto-generated by build.sh **/
/**
 * App: Global Utilities & Template Engine
 */
const App = {
    async loadTemplate(url, data = {}) {
        try {
            const res = await fetch(url);
            if (!res.ok) throw new Error(`Missing: ${url}`);
            let template = await res.text();
            
            // Recursive path resolver for {{ object.key }}
            return template.replace(/{{\s*([\w.]+)\s*}}/g, (_, path) => {
                const value = path.split('.').reduce((obj, key) => obj?.[key], data);
                if (typeof value === 'boolean') return value ? '<span class="text-success">ONLINE</span>' : '<span class="text-danger">OFFLINE</span>';
                return value ?? '';
            });
        } catch (e) {
            return `<div class="p-4 text-danger">Template Error: ${e.message}</div>`;
        }
    },
    crm() { Model.currentPage = 'home'; Controller.render(); },
    cyberdeck() { Model.currentPage = 'llm'; Controller.render(); },
    url(path) { 
    	// Ensure the path does not start with a / to avoid double slashes
    	const cleanPath = path.startsWith('/') ? path.substring(1) : path;
    	return `${window.location.origin}/php/${cleanPath}`; 
    },
    selectList(fields, callback) {
    const select = document.createElement('select');
    select.className = 'agent-selector'; // For CSS styling

    // Add a default placeholder
    const defaultOption = document.createElement('option');
    defaultOption.text = 'Select an agent...';
    defaultOption.value = '';
    select.appendChild(defaultOption);

    // Build the fields
    fields.forEach(field => {
        const option = document.createElement('option');
        option.value = field.id;
        option.text = field.name;
        select.appendChild(option);
    });

    // Use onchange for select elements
    select.onchange = function(e) {
        if (this.value) {
            callback(this.value);
        }
    };

    return select;
    },
    getApp() { return document.getElementById('app'); },
    item(e) { return document.createElement(e); },
    flash(msg) {
        const flash = document.getElementById('flash');
        if (!flash) return;
        const alert = App.item('div');
        alert.style.cssText = 'width:100%;border-radius:16px;margin-bottom:10px;padding-top:10px;padding-bottom:10px;background-color:#ccc;text-align:center';
        alert.innerHTML = msg;
        flash.appendChild(alert);
    },
    getItem(e){return document.getElementById(e)},
};



// Add this helper to App
App.addAgentActions = function(form) {
    // Only proceed if we are in agent context
    const agentId = document.getElementById('agent_id');
    if (!agentId || !agentId.value) return;

    const actions = [
        "Deploy latest container", "Rotate SSH keys", "Scale worker nodes", 
        "Execute maintenance script", "Clear orphaned containers", 
        "Backup database volume", "Audit security logs", "Restart Nginx", 
        "Purge temporary files", "Verify integrity"
    ];

    const label = App.item('label');
    label.innerHTML = "Agent Task Actions";
    form.appendChild(label);

    const select = document.createElement('select');
    select.className = 'form-control mb-2';
    select.innerHTML = '<option value="">-- Choose an action --</option>';

    actions.forEach(action => {
        const opt = document.createElement('option');
        opt.value = action;
        opt.text = action;
        select.appendChild(opt);
    });

    select.onchange = (e) => {
        if (e.target.value) {
            const body = document.getElementById('body');
            body.value += (body.value ? "\n" : "") + `Action: ${e.target.value}`;
        }
    };
    form.appendChild(select);
};

App.agentEmailForm = function(agent) {
    // 1. Navigate to the email page
    Controller.navigate('emails');

    // 2. Wait for the form to be rendered by the router
    setTimeout(() => {
        const form = document.getElementById('form');
        const subject = document.getElementById('subject');

        if (subject) {
            subject.value = `Task for: ${agent.agent_name}`;
        }

        // 3. Add hidden agent context to associate the task
        const hidden = document.createElement('input');
        hidden.type = 'hidden';
        hidden.id = 'agent_id';
        hidden.value = agent.id;
        form.appendChild(hidden);

        // 4. Inject agent-specific form options/metadata
        const info = document.createElement('div');
        info.className = 'mt-2 p-2 border bg-light';
        info.innerHTML = `<strong>Agent Context:</strong> ${agent.role} active.`;
        form.appendChild(info);

        App.flash(`Agent ${agent.agent_name} loaded into email form.`);
    }, 100);
};
App.eForm = function(form, schema) {
    form.innerHTML = '';
    Object.keys(schema).forEach(key => {
        const field = schema[key];
        const id = field.id || key;
        const type = field.type || 'text';
        
        // Create element: Textarea if defined, else input
        const el = App.item(type === 'textarea' ? 'textarea' : 'input');
        el.id = id;
        el.className = 'form-control';
        
        if (field.placeholder) el.placeholder = field.placeholder;
        if (type !== 'textarea') el.type = type;

        const label = App.item('label');
        label.className = 'form-label fw-bold';
        label.textContent = key.charAt(0).toUpperCase() + key.slice(1);
        
        const row = App.item('div');
        row.className = 'mb-3';
        row.appendChild(label);
        row.appendChild(el);
        form.appendChild(row);
    });
};

App.log = function(log){
    console.log(log);
};/**
 * Enhanced App Debug Utility
 * @param {any} data - Message, Object, or Error to inspect
 * @param {string} [label='DEBUG'] - Context tag/label
 * @param {string} [level='log'] - Console level: 'log', 'info', 'warn', 'error', 'table'
 */
App.debug = function (data, label = 'DEBUG', level = 'log') {
    const timestamp = new Date().toTimeString().split(' ')[0];
    const prefix = `[${timestamp}] [${label}]`;

    // 1. Structured Console Grouping
    if (typeof console[level] === 'function') {
        console.groupCollapsed(`%c${prefix}`, 'color: #007acc; font-weight: bold;', 
            typeof data === 'string' ? data : (data?.title || data?.action || typeof data)
        );
        
        if (typeof data === 'object' && data !== null) {
            console.dir(data);
            if (Array.isArray(data)) {
                console.table(data);
            }
        } else {
            console[level](data);
        }

        console.trace('Execution Trace');
        console.groupEnd();
    } else {
        console.log(prefix, data);
    }

    // 2. On-Screen Overlay Rendering (for Mobile debugging without DevTools)
    const overlay = document.getElementById('debug-output');
    if (overlay) {
        const entry = document.createElement('pre');
        entry.style.cssText = `
            margin: 4px 0;
            padding: 8px;
            background: #1e1e1e;
            color: ${level === 'error' ? '#ff6b6b' : level === 'warn' ? '#fca5a5' : '#4ade80'};
            font-family: monospace;
            font-size: 11px;
            border-left: 3px solid ${level === 'error' ? '#ef4444' : '#22c55e'};
            white-space: pre-wrap;
            word-break: break-all;
        `;

        const formattedContent = typeof data === 'object' ? JSON.stringify(data, null, 2) : String(data);
        entry.textContent = `${prefix}\n${formattedContent}`;
        overlay.prepend(entry);
    }
};/**
 * Global dBug Renderer
 * Converts a JS variable recursively into styled, collapsible HTML tables.
 */
App.dBug = function(data, typeName = null) {
    if (data === null || data === undefined) {
        const cell = document.createElement('span');
        cell.style.fontWeight = 'bold';
        cell.style.fontStyle = 'italic';
        cell.textContent = 'NULL';
        return cell;
    }

    if (typeof data === 'boolean') {
        const cell = document.createElement('span');
        cell.style.fontWeight = 'bold';
        cell.style.fontStyle = 'italic';
        cell.textContent = data ? 'TRUE' : 'FALSE';
        return cell;
    }

    if (typeof data !== 'object') {
        const cell = document.createElement('span');
        cell.style.fontFamily = 'Verdana, Arial, Helvetica, sans-serif';
        cell.style.fontSize = '12px';
        cell.textContent = String(data).trim() === '' ? '[empty string]' : String(data);
        return cell;
    }

    const isArr = Array.isArray(data);
    const type = typeName || (isArr ? 'array' : 'object');

    const isArrayType = type === 'array';
    const theme = {
        tableBg: isArrayType ? '#006600' : '#0000CC',
        borderColor: isArrayType ? 'green' : 'blue',
        headerBg: isArrayType ? '#009900' : '#4444CC',
        keyBg: isArrayType ? '#CCFFCC' : '#CCDDFF'
    };

    const table = document.createElement('table');
    table.className = `dBug_${type}`;
    table.style.fontFamily = 'Verdana, Arial, Helvetica, sans-serif';
    table.style.color = '#000000';
    table.style.fontSize = '12px';
    table.style.backgroundColor = theme.tableBg;
    table.style.border = `1px solid ${theme.borderColor}`;
    table.style.borderCollapse = 'separate';
    table.style.borderSpacing = '2px';
    table.style.margin = '4px auto';
    table.style.width = '90%';

    // Header Row
    const headerTr = document.createElement('tr');
    const headerTd = document.createElement('td');
    headerTd.className = `dBug_${type}Header`;
    headerTd.setAttribute('colspan', '2');
    headerTd.textContent = type;
    headerTd.style.backgroundColor = theme.headerBg;
    headerTd.style.border = `1px solid ${theme.borderColor}`;
    headerTd.style.color = '#FFFFFF';
    headerTd.style.fontWeight = 'bold';
    headerTd.style.cursor = 'pointer';
    headerTd.style.padding = '3px';

    headerTd.addEventListener('click', () => {
        const rows = table.querySelectorAll(':scope > tr:not(:first-child)');
        const isHidden = Array.from(rows).some(r => r.style.display === 'none');
        rows.forEach(r => r.style.display = isHidden ? '' : 'none');
        headerTd.style.fontStyle = isHidden ? 'normal' : 'italic';
    });

    headerTr.appendChild(headerTd);
    table.appendChild(headerTr);

    // Body Rows
    const entries = Object.entries(data);
    if (entries.length === 0) {
        const emptyTr = document.createElement('tr');
        const emptyTd = document.createElement('td');
        emptyTd.setAttribute('colspan', '2');
        emptyTd.style.backgroundColor = '#FFFFFF';
        emptyTd.style.border = `1px solid ${theme.borderColor}`;
        emptyTd.style.padding = '3px';
        emptyTd.textContent = '[empty]';
        emptyTr.appendChild(emptyTd);
        table.appendChild(emptyTr);
        return table;
    }

    entries.forEach(([key, val]) => {
        const tr = document.createElement('tr');

        const keyTd = document.createElement('td');
        keyTd.className = `dBug_${type}Key`;
        keyTd.textContent = key;
        keyTd.style.backgroundColor = theme.keyBg;
        keyTd.style.border = `1px solid ${theme.borderColor}`;
        keyTd.style.cursor = 'pointer';
        keyTd.style.padding = '3px';
        keyTd.style.verticalAlign = 'top';

        keyTd.addEventListener('click', () => {
            const valTd = tr.children[1];
            if (valTd) {
                valTd.style.display = valTd.style.display === 'none' ? '' : 'none';
            }
        });

        const valTd = document.createElement('td');
        valTd.style.backgroundColor = '#FFFFFF';
        valTd.style.border = `1px solid ${theme.borderColor}`;
        valTd.style.padding = '3px';
        
        // Recursive call to App.dBug
        valTd.appendChild(App.dBug(val));

        tr.append(keyTd, valTd);
        table.appendChild(tr);
    });

    return table;
};/* app_spinner.js */
App.spinner = function(){
    const spinner = document.getElementById('spinner');
    if (spinner) spinner.style.display = 'flex'; // Make it visible
};

App.clearSpinner = function(){
    const spinner = document.getElementById('spinner');
    if (spinner) spinner.style.display = 'none'; // Hide it again
};/** app_modal.js */
App.modal = {
    open(content, options = {}) {
        const {
            closeOnBackdrop = true,
            closeOnEscape = true,
            className = '',
            id = ''
        } = options;

        // Create elements
        const overlay = document.createElement('div');
        overlay.id = 'app-modal-overlay';
        overlay.className = 'app-modal-overlay'; // Managed by CSS

        const modal = document.createElement('div');
        modal.className = `modal-content ${className}`; // Managed by CSS
        modal.innerHTML = content;
        if (id) modal.id = id;
        

        overlay.appendChild(modal);
        document.body.appendChild(overlay);

        // Event management
        if (closeOnBackdrop) {
            overlay.onclick = (e) => {
                if (e.target === overlay) this.close();
            };
        }

        if (closeOnEscape) {
            const onKey = (e) => { if (e.key === 'Escape') this.close(); };
            document.addEventListener('keydown', onKey);
            overlay._modalKeyHandler = onKey;
        }
    },
    
    close() {
        const overlay = document.getElementById('app-modal-overlay');
        if (!overlay) return;
        
        if (overlay._modalKeyHandler) {
            document.removeEventListener('keydown', overlay._modalKeyHandler);
        }
        overlay.remove();
    }
};/**
 * TikTok Controller: UX Enhanced
 */
const TiktokController = {
    async bindPosts() {
        // App.loadView (if needed) - assumes HTML is already injected
        const btn = document.getElementById('tiktok-submit');
        const contentInput = document.getElementById('tiktok-content');

        if (!btn || !contentInput) return;

        btn.onclick = (e) => {
            // Visual feedback: brief pulse
            btn.style.opacity = '0.5';
            setTimeout(() => btn.style.opacity = '1', 200);

            AgentController.tiktokPost(contentInput.value);
        };
    }
};
/**
 * Agent Controller
 */
const AgentController = {
    // Add to your existing AgentController object
    tiktokPost: function(content) {
    if (!content.trim()) {
        App.flash('Please enter some content first.');
        return;
    }

    const dialog = App.item('div');
    dialog.className = 'border p-3 mt-3 bg-warning';
    dialog.innerHTML = `
        <h5>Confirm TikTok Post</h5>
        <p>Posting: <em>${content}</em></p>
        <button id="tiktok-confirm" type="button" class="btn btn-dark">Confirm & Post</button>
    `;
    
    // Mount within the app container for consistent styling
    const host = document.getElementById('app') || document.body;
    host.appendChild(dialog);

    document.getElementById('tiktok-confirm').onclick = () => {
        // Dummy API Response Logic
        const mockResponse = { status: 'success', id: 'tt_' + Math.random().toString(36).substr(2, 9) };
        
        App.flash('TikTok post queued: ' + mockResponse.id);
        dialog.remove();
        
        // Clear input after success
        const contentInput = document.getElementById('tiktok-content');
        if (contentInput) contentInput.value = '';
    };
},
// Note the 'async' keyword here
async bindAgentsDefault(){
    const form = App.getItem('form');
    
    // Await the result so it resolves to the actual HTML string
    const html = await App.loadTemplate('views/pages/welcome.html', {'foo':'bar'});
    
    // Now you have the string, not the Promise
    form.innerHTML = html;
},
    async bindAgents() {
        this.bindAgentsDefault();
        const fields = { 'create': {}, 'read': {}};
        const menu = document.getElementById('menu');
        if (menu) Controller.menuFields(fields, menu);
    },
    contacts: function(form) {
        const container = App.item('div');
        container.id = 'agent-contacts-container';
        container.className = 'mt-3 p-2 border';
        
        // 1. Add Title first
        const title = App.item('h5');
        title.innerHTML = 'Available Contacts';
        container.appendChild(title);

        // 2. Populate contacts inside the container
        this.address(container);
        
        form.appendChild(container);
        return container;
    },

    address: function(container) {
        const contacts = [
            { name: "Admin", email: "admin@system.local" },
            { name: "DevOps", email: "devops@system.local" }
        ];

        contacts.forEach(c => {
            const btn = App.item('button');
            btn.className = 'btn btn-sm btn-secondary m-1';
            btn.innerHTML = c.name;
            
            // Set the 'to' field when clicked
            btn.onclick = (e) => {
                e.preventDefault();
                const toField = document.getElementById('to');
                if (toField) toField.value = c.email;
            };
            
            container.appendChild(btn);
        });
    },
    // Add to Controller object
    async displayAgentRecords(form) {
        form.innerHTML = '<h3>Active Agents</h3>';
        
        // Fetch existing agents
        try {
            const res = await fetch(App.url('agent/index')); // Assumes your AgentController exists
            const agents = await res.json();
            console.log(agents);
            const table = App.item('table');
            table.className = 'agent-table';
            table.innerHTML = `<thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead>`;
            const tbody = App.item('tbody');

            agents.forEach(agent => {
        const tr = App.item('tr');
        
        // Define your actions
        const actions = [
            {id: 'autoform', name: 'Automatic Form Completion'},
            {id: 'snapshot', name: 'Ingestion external form'},
            {id: 'tiktok', name: 'Tiktok'},
            {id: 'pentest',name: 'Penetration Testing'},
            {id: 'pension',name: 'Pension Schemes'},
        ];

        // Build standard cells using template literals for safe, static content
        tr.innerHTML = `
            <td>${agent.agent_name}</td>
            <td>${agent.role}</td>
            <td><span class="badge ${agent.status}">${agent.status}</span></td>
        `;

        // Create the select cell
        const actionTd = document.createElement('td');
        const select = App.selectList(actions, (actionId) => {

        // TODO: Create loop
        // pages [{}];

        if (actionId === 'snapshot') {

            Controller.navigate(actionId);

        } else if (actionId === 'pentest') {

            Controller.navigate(actionId);

        } else if (actionId === 'autoform') {

            Controller.navigate(actionId );

        } else  if (actionId === 'tiktok') {

            Controller.navigate(actionId );

        } else if (actionId === 'email') {

            Controller.navigate(actionId );

        } else {
            // Handle other actions (start, stop, etc.)
            console.log(`Action ${actionId} selected for agent ${agent.agent_name}`);
        }

        });
        
        actionTd.appendChild(select);
        tr.appendChild(actionTd);
        
        tbody.appendChild(tr);
    });
            table.appendChild(tbody);
            form.appendChild(table);
        } catch (e) {
            form.innerHTML += '<p>No agents found or error loading.</p>';
        }
    },
};

AgentController.bindAgentEmail = function() {
    const container = document.getElementById('email-fields');
    const sendRow = document.getElementById('send-button');
    if (!container || !sendRow) return;

    // Schema: Keys are labels, Values contain technical attributes
    const schema = { 
        'email': { 'id': 'to', 'placeholder': 'recipient@example.com' }, 
        'title':  { 'id': 'subject', 'placeholder': 'Subject line' }, 
        'content': { 'id': 'message', 'type': 'textarea', 'placeholder': 'Email body...' } 
    };

    App.eForm(container, schema);

    if (!document.getElementById('send-btn')) {
        const btn = App.item('button');
        btn.id = 'send-btn';
        btn.type = 'button';
        btn.className = 'btn btn-primary';
        btn.innerHTML = 'Queue Email Task';
        
        btn.onclick = () => {
            // Correctly targeting the IDs generated by App.eForm
            AgentController.emailQueue(
                document.getElementById('to'),
                document.getElementById('subject'),
                document.getElementById('message')
            );
        };
        sendRow.appendChild(btn);
    }
};

AgentController.emailQueue = function(toInput, subjectInput, bodyInput) {
    // 1. Basic validation
    if (!toInput.value || !toInput.value.includes('@')) {
        App.flash('Please enter a valid email address.');
        return;
    }

    const btn = document.getElementById('send-btn');
    if (btn) btn.disabled = true; // Disable button to prevent double-submit

    const payload = {
        email: toInput.value.trim(),
        title: subjectInput.value.trim(),
        content: bodyInput.value.trim(),
        status: 'waiting'
    };

    const uniqueId = 'email_' + Date.now().toString(36) + '_' + Math.random().toString(36).substr(2, 5);

    fetch(App.url(`emails/queue/${uniqueId}`), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
    })
    .then(res => res.json())
    .then(result => {
        if (result.status === 'success') {
            App.flash('Successfully queued: ' + result.id);
            toInput.value = '';
            subjectInput.value = '';
            bodyInput.value = '';
        } else {
            App.flash('Error: ' + (result.message || 'Persistence failure'));
        }
    })
    .catch(err => {
        App.flash('Connection error: ' + err.message);
    })
    .finally(() => {
        if (btn) btn.disabled = false; // Re-enable button
    });
};

AgentController.tiktokPost = function(content) {
    if (!content.trim()) {
        App.flash('The feed is empty! Give us something viral.');
        return;
    }

    const dialog = App.item('div');
    dialog.className = 'card mt-4 p-4 border-2 border-danger'; // High-visibility border
    dialog.innerHTML = `
        <h5 style="color: #dc3545;">⚠️ Broadcast Authorization</h5>
        <p>You are about to launch this content to TikTok:</p>
        <div class="p-3 bg-light border mb-3"><em>"${content}"</em></div>
        <button id="tiktok-confirm" class="btn btn-outline-primary mt-2" style="width: 100%;">
            CONFIRM & LAUNCH
        </button>
    `;
    
    const host = document.getElementById('app');
    host.appendChild(dialog);

    document.getElementById('tiktok-confirm').onclick = () => {
        const mockResponse = { status: 'success', id: 'viral_' + Math.random().toString(36).substr(2, 5) };
        
        App.flash('🚀 Posted to TikTok: ' + mockResponse.id);
        dialog.remove();
        document.getElementById('tiktok-content').value = '';
    };
};

AgentController.autoForm = function() {
    const container = App.getItem('autoform-container');
    container.innerHTML = '<h3>Automatic Form Completion</h3>';

    // Create a form container
    const form = App.item('div');
    form.id = 'autoform-container';
    container.appendChild(form);

    // Schema for target platforms
    const schema = {
        'Job Source': { 'id': 'source', 'placeholder': 'e.g., jobs.com' },
        'Role': { 'id': 'role', 'placeholder': 'Software Developer' },
        'Experience': { 'id': 'exp', 'placeholder': 'Years of experience' }
    };

    // Use App.eForm to build the interface
    App.eForm(form, schema);

    // Add Submit Action
    const btn = App.item('button');
    btn.className = 'btn btn-primary mt-3';
    btn.innerHTML = 'Execute Auto-Fill';
    btn.onclick = () => {
        const data = {
            source: document.getElementById('source').value,
            role: document.getElementById('role').value,
            exp: document.getElementById('exp').value
        };
        App.flash('Initiating auto-form completion for ' + data.source);
        console.log('Payload:', data);
    };
    
    form.appendChild(btn);
    const url = 'ingestion/save/?url=https://www.applybe.com/?a=145F80311.0';
    AgentController.formPreview(url);
};

// Ensure 'async' is present to use 'await'
AgentController.formPreview = async function(url) {
    const preview = document.getElementById('preview');
    if (!preview) return; // Guard clause

    App.spinner();
    try {
        const response = await fetch(App.url(url));
        if (!response.ok) throw new Error('Failed to fetch preview');
        
        const html = await response.text();
        preview.innerHTML = html;
    } catch (e) {
        // Corrected from e.getMessage() to e.message
        App.flash('Error: ' + e.message);
    } finally {
        App.clearSpinner();
    }
};/**
 * Agentic Controller
 */
const AgenticController = {
    init() {
        const data = {foo: 'bar',app: App};
        console.log(data);
    }
};

/** controllers.js **/



/**
 * Rag Controller
 */
const RagController = {
        async bindRag() {
        const btn = document.getElementById('rag-send');
        const input = document.getElementById('rag-input');
        const history = document.getElementById('chat-history');
        if (!btn) return;

        btn.onclick = async () => {
            const query = input.value.trim();
            if (!query) return;
            history.innerHTML += `<p><strong>You:</strong> ${query}</p>`;
            input.value = '';
            
            App.spinner(); // Minimal change: Start spinner
            
            try {
                // Changed from POST/body to GET/URL query parameter
                const url = App.url('rag/rag/') + encodeURIComponent(query);
                const res = await fetch(url, {
                    method: 'GET'
                });
                const data = await res.json();
                history.innerHTML += `<p><strong>Bot:</strong> ${data.answer || data.message}</p>`;
            } catch (e) { history.innerHTML += `<p class="text-danger">Error: Service unavailable</p>`; }
            finally {
                App.clearSpinner(); // Minimal change: Stop spinner
            }
            
            history.scrollTop = history.scrollHeight;
        };
    },
};

/**
 * Llm Controller
 */
const LlmController = {};


/**
 * Docs Controller
 */
const DocsController = {};

/**
 * Sales Controller
 */
const SalesController = {
    async bindSales() {
        // 1. Load the page shell into the app container
        const target = document.getElementById('app');
        target.innerHTML = await App.loadTemplate('/views/sales/index.html');

        // 2. Now that the HTML is in the DOM, fetch and render the data
        const salesContainer = document.getElementById('sales-list');
        try {
            const res = await fetch(App.url('/views/sales/leads')); 
            const sales = await res.json();
            
            salesContainer.innerHTML = sales.map(s => `
                <tr>
                    <td>${s.company}</td>
                    <td>${s.tier}</td>
                    <td>${s.status}</td>
                    <td><button class="btn btn-sm btn-outline-info">Edit</button></td>
                </tr>
            `).join('');
        } catch (e) {
            salesContainer.innerHTML = '<tr><td colspan="4">Error loading data.</td></tr>';
        }
    }
};

/**
 * Leads Controller: Manages lead intake and feedback
 */
const LeadsController = {
    async loadLeads() {
        const feed = document.getElementById('leads-feed');
        if (!feed) return;
        try {
            const res = await fetch(App.url('lead/index'));
            const data = await res.json();
            feed.innerHTML = data.map(l => `
                <div class="list-group-item">
                    <strong>${l.name || 'Anonymous'}</strong>: ${l.notes}
                </div>
            `).join('');
        } catch (e) {
            feed.innerHTML = '<div class="text-danger">Error loading leads.</div>';
        }
    },

    async saveLead(formData) {
        const payload = Object.fromEntries(formData);
        await fetch(App.url('lead/log'), {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        this.loadLeads(); // Refresh after save
    }
};




/**
 * Controller: Orchestrates UI logic, data fetching, and event binding
 */
const Controller = {
    async autoFill() {
        const input = document.getElementById('autocomplete');
        if (!input) return;
        const ul = document.createElement('ul');
        const li = document.createElement('li');
        li.innerHTML = "test";
        ul.appendChild(li);
        input.appendChild(ul);
    },



    eFields(fields) {
        let post = {};
        for (let field in fields) {
            const el = document.getElementById(field);
            post[field] = el ? el.value : '';
        }
        return post;
    },

    eForm(form, fields) {
        for (let field in fields) {
            const input = App.item('input');
            input.setAttribute('id', field);
            const label = App.item('label');
            label.innerHTML = field;
            const row = App.item('div');
            row.appendChild(label);
            row.appendChild(input);
            form.appendChild(row);
        }
    },

    async bindEmails() {
    const fields = { 'to': {}, 'subject': {}, 'body': {} };
    const form = document.getElementById('form');
    if (!form) return;
    
    // Clear the form and re-render only the fields
    form.innerHTML = '';
    this.eForm(form, fields);

    const btn = App.item('button');
    btn.type = 'button';
    btn.className = 'btn btn-outline-primary mt-2';
    btn.innerHTML = "Queue Email Task";
    form.appendChild(btn);

    btn.onclick = (e) => {
        e.preventDefault();
        
        const toInput = document.getElementById('to');
        const subjectInput = document.getElementById('subject');
        const bodyInput = document.getElementById('body');
        
        // Use the reverted, clean emailQueue
        AgentController.emailQueue(toInput, subjectInput, bodyInput);
    };
},






async menuFields(fields, menu) {
    for (let field in fields) {
        let item = App.item('div');
        item.innerHTML = field;
        item.id = field;
        item.classList.add('menu-item'); // Use the CSS class
        
        item.onclick = async () => {
            let form = document.getElementById('form');
            if (!form) return;

            // Clear current form if necessary or reset state
            this.handleMenuClick(field, form);
        };
        menu.appendChild(item);
    }
},

// Controller method to handle the logic switch
handleMenuClick(field, form) {
    switch(field) {
        case 'create':
            this.createAgent(form);
            break;
        case 'read':
            AgentController.displayAgentRecords(form);
            break;
        case 'delete':
            let msg = App.item('div');
            msg.innerHTML = "Create a new agent to do the tasks you avoid";
            form.appendChild(msg);
            break;
    }
},

    // Triggered by the 'create' menu item
    createAgent(form) {
        // 1. Clear existing form content
        form.innerHTML = '';
        
        // 2. Define fields for the agent creation
        const fields = { 
            'agent_name': {}, 
            'description': {}, 
            'role': {} 
        };
        
        // 3. Populate form using your existing helper
        this.createAgentForm(form, fields);
        
        // 4. Add a submit button
        const btn = App.item('div');
        btn.style.cssText = 'cursor:pointer;border:1px dashed #ccc; margin-top: 10px; padding: 5px;';
        btn.innerHTML = "Save Agent";
	// 5. Post form data
        btn.onclick = async () => {
            const postData = this.eFields(fields);
            try {
                const res = await fetch(App.url('agent/test/'), {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(postData)
                });
                const data = await res.json();
                App.flash('Success id:' + data.id + ' created');
            } catch (e) { App.flash('Error'); }
        };

	//
        form.appendChild(btn);
    },

    // Handles looping through fields and injecting them into the form
    createAgentForm(form, fields) {
        // Reuse your existing logic, or use eForm if it matches perfectly
        this.eForm(form, fields);
    },    
    async init() {
        const host = window.location.hostname;
        const sub = host.split('.')[0];
        try {
            const res = await fetch('views/layouts/header.html');
            if (res.ok) {
                let headerTemplate = await res.text();
                const initialH1 = (sub === 'cyberdeck') ? 'Cyberdeck (LLM)' : 'Thomasons V3';
                document.getElementById('header').innerHTML = headerTemplate.replace(/{{\s*h1\s*}}/g, initialH1);
            }
        } catch (e) { console.error("Layout Engine init failed:", e); }

        // Trigger cookie consent immediately after init
        this.showCookieConsent();

        if (sub === 'crm') App.crm();
        else if (sub === 'cyberdeck') App.cyberdeck();
        else this.navigate('home');

        document.addEventListener('click', (e) => {
            const page = e.target.closest('[data-page]')?.dataset.page;
            if (page) { e.preventDefault(); this.navigate(page); }
        });
        App.spinner();
        App.clearSpinner();
    },

    showCookieConsent() {
        App.modal.open(`
            <h3>Cookie Policy</h3>
            <p>We use cookies to enhance your neural-pipeline experience. Do you accept our terms?</p>
            <div style="display:flex; gap:10px; justify-content:end; margin-top:20px;">
                <button id="btn-reject" class="btn btn-outline-secondary">Reject</button>
                <button id="btn-accept" class="btn btn-primary">Accept</button>
            </div>
        `, { closeOnBackdrop: false, closeOnEscape: false });

        document.getElementById('btn-accept').onclick = () => {
            console.log("Cookies accepted");
            App.modal.close();
        };

        document.getElementById('btn-reject').onclick = () => {
            console.log("Cookies rejected");
            App.modal.close();
        };
    },

    async render() {
        const target = document.getElementById('app');
        if (!target) return;

        const templatePath = Model.currentPage === 'home' 
            ? 'views/home/index.html' 
            : `views/pages/${Model.currentPage}.html`;

        let html = await App.loadTemplate(templatePath, {
            health: Model.healthStatus,
            queue: Model.queue
        });

        const headerH1 = document.querySelector('#header h1');
        if (headerH1) headerH1.textContent = Model.currentPage === 'home' ? 'Thomasons V3' : Model.currentPage.toUpperCase();
        
        document.querySelectorAll('.navbar .nav-link').forEach(link => {
            link.classList.toggle('active', link.dataset.page === Model.currentPage);
        });

        if (Model.currentPage === 'llm') {
            const itemsHtml = Model.queue.map(item => `
                <div class="card mb-2 p-2 small border-0 shadow-sm">
                    <div class="d-flex justify-content-between">
                        <strong>${item.name}</strong>
                        <span class="text-primary">${item.status}</span>
                    </div>
                </div>
            `).join('');
            html = html.replace('{{ queueHtml }}', itemsHtml || '<p class="text-muted small">No active jobs.</p>');
        }

        target.innerHTML = `<div class="fade-in">${html}</div>`;
        this.bindEvents();
        if (PageRegistry[Model.currentPage]) PageRegistry[Model.currentPage]();
    },

    navigate(page) { 
        
        const debug = {page: page};

        console.log(debug);
        
        Model.currentPage = page; this.render(); 

    },

    bindEvents() {
        const drop = document.getElementById('dropzone');
        const input = document.getElementById('fileInput');
        if (!drop || !input) return;

        drop.onclick = () => input.click();
        input.onchange = (e) => this.handleUpload(e.target.files);
        drop.ondragover = (e) => { e.preventDefault(); drop.style.backgroundColor = '#f0f7ff'; };
        drop.ondragleave = () => drop.style.backgroundColor = '';
        drop.ondrop = (e) => {
            e.preventDefault();
            drop.style.backgroundColor = '';
            this.handleUpload(e.dataTransfer.files);
        };
    },

    async handleUpload(files) {
        if (!files.length) return;
        const formData = new FormData();
        Array.from(files).forEach(f => {
            formData.append('documents[]', f);
            Model.queue.push({ name: f.name, status: 'processing', progress: 25 });
        });
        this.render();

        // Call the view update
        view.neuralPipeline();

        try {
            const res = await fetch(App.url('job/create'), { method: 'POST', body: formData });
            const result = await res.json(); // Capture the server response

            if (result.status === 'success') {
                Model.queue.forEach(item => { item.status = 'queued'; item.progress = 50; });
                this.render();

                // Hook into the JobProgressController for background monitoring
                JobProgressController.monitor(
                    result.job_id, 
                    (data) => {
                        App.flash("Pipeline Complete: " + data.message);
                        // Optional: Trigger a UI refresh to show the file as "processed"
                    },
                    (err) => {
                        App.flash("Pipeline Error: " + err.message);
                    }
                );
            }
        } catch (e) { 
            console.error("Upload failed", e);
            App.flash("Upload failed: Check network connection.");
        }
    },

    docsBindMessage(record, ul) {
        let li = document.createElement('li');
        li.innerHTML = '<b>You</b>:&nbsp;' + record.message;
        ul.appendChild(li);
    },
    docsBindAnswer(record, ul) {
        let li = document.createElement('li');
        li.innerHTML = '<b>Sharpishly</b>:&nbsp;' + record.answer;
        ul.appendChild(li);
    },
    async docs(page) {
        try {
            const res = await fetch(App.url('docs'));
            const data = await res.json();
            const target = document.getElementById('app');
            let ul = document.createElement('ul');
	    ul.setAttribute('id','docs');
            for (let id in data.records) {
                this.docsBindMessage(data.records[id], ul);
                this.docsBindAnswer(data.records[id], ul);
            }
            if (target) target.appendChild(ul);
        } catch (e) { }
    }
};
const JobProgressController = {
    monitor: function(jobId, onComplete, onError) {
        const interval = setInterval(async () => {
            try {
                const response = await fetch(`/php/job/status/${jobId}`);
                const data = await response.json();
                
                // 1. Update the UI directly
                const pipelineDiv = document.getElementById('neural-pipeline');
                if (pipelineDiv) {
                    pipelineDiv.innerHTML = `
                        <div class="alert alert-info">
                            Job #${jobId} status: <strong>${data.state}</strong>
                        </div>
                    `;
                }

                // 2. Lifecycle management
                if (data.state === 'completed') {
                    clearInterval(interval);
                    onComplete(data);
                } else if (data.state === 'failed') {
                    clearInterval(interval);
                    onError(data);
                }
            } catch (error) {
                console.error("Polling error:", error);
                clearInterval(interval);
            }
        }, 2000);
    }
};/** 
 * HealthController: Orchestrates the Health Center UI
 * Pattern: Defensive DOM initialization + Robust Payload Handling
 */
const HealthController = {
    elements: {},
    pollTimer: null,

    // Ensure DOM elements are mapped once, when they exist
    init() {
        this.elements = {
            rag: App.getItem('status-rag'),
            worker: App.getItem('status-worker'),
            ollama: App.getItem('status-ollama'),
            models: App.getItem('status-models')
        };
    },

    // Main fetch with spinner
    async get() {
        if (Object.keys(this.elements || {}).length === 0) this.init();
        
        App.spinner();
        try {
            const res = await fetch(App.url('health'));
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            
            const data = await res.json();

            // Normalize data from response
            this.rag(data.rag_service);
            this.ollama(data.ollama);
            this.worker(data.worker);
            this.models(data.models);

        } catch (e) {
            console.error("Health Center unreachable:", e);
            this.rag('unreachable'); 
            App.flash(`Health Center Error: Service unreachable`);
        } finally {
            App.clearSpinner();
        }
    },

    // Silent background poll without global spinner
    async getSilent() {
        if (Object.keys(this.elements || {}).length === 0) this.init();
        try {
            const res = await fetch(App.url('health'));
            if (!res.ok) return;
            
            const data = await res.json();
            this.rag(data.rag_service);
            this.ollama(data.ollama);
            this.worker(data.worker);
            this.models(data.models);
        } catch (e) {
            console.error('Health poll error:', e);
        }
    },

    // Isolated polling lifecycle tied to DOM state
    startPolling(intervalMs = 10000) {
        this.stopPolling();
        this.get();

        this.pollTimer = setInterval(() => {
            const el = document.getElementById('health');
            if (!el || !document.body.contains(el)) {
                this.stopPolling();
                return;
            }
            this.getSilent();
        }, intervalMs);
    },

    stopPolling() {
        if (this.pollTimer) {
            clearInterval(this.pollTimer);
            this.pollTimer = null;
        }
    },

    async testSuite() {
        console.log('HealthController.testSuite: Starting suite execution...');

        const healthContainer = document.getElementById('health');
        if (!healthContainer) {
            console.warn('HealthController.testSuite: #health container missing from DOM.');
            return;
        }

        let suiteContainer = document.getElementById('health-test-suite');
        if (!suiteContainer) {
            suiteContainer = document.createElement('div');
            suiteContainer.id = 'health-test-suite';
            suiteContainer.className = 'card shadow-sm border-0 mt-4 p-4';
            healthContainer.appendChild(suiteContainer);
        }

        // 1. Render immediate placeholders for every response key in TestController
        const expectedKeys = [
            'id',
            'class',
            'function',
            'google_api',
            'hotmail_api',
            'azure_api',
            'aws_api',
            'recent_work',
            'orm',
            'llm'
        ];

        const placeholderItems = expectedKeys.map(key => 
            `<li><strong class="tree-key">${this.escapeHtml(key)}:</strong> <span class="tree-val text-muted">[CHECKING...]</span></li>`
        ).join('');

        suiteContainer.innerHTML = `
            <h3 class="fw-bold mb-3 fs-5">Test Suite Output</h3>
            <ul class="tree-node tree-object">${placeholderItems}</ul>
        `;

        console.log('HealthController.testSuite: Placeholders rendered. Requesting test data...');
        App.spinner();

        try {
            const res = await fetch(App.url('test/health'));
            console.log(`HealthController.testSuite: Response received with HTTP status ${res.status}`);

            if (!res.ok) throw new Error(`HTTP ${res.status}`);

            const data = await res.json();
            console.log('HealthController.testSuite: Payload decoded successfully:', data);

            // 2. Overwrite placeholders with recursive data tree
            suiteContainer.innerHTML = `
                <h3 class="fw-bold mb-3 fs-5">Test Suite Output</h3>
                ${this.renderTree(data)}
            `;
        } catch (e) {
            console.error('HealthController.testSuite: Execution failed with error:', e);
            App.flash('Health Center Error: Test suite unreachable');
        } finally {
            App.clearSpinner();
            console.log('HealthController.testSuite: Execution finished.');
        }
    },

    // Recursive object tree renderer
    renderTree(nodes) {
        if (nodes === null || nodes === undefined) return '<span class="tree-null">null</span>';
        if (typeof nodes !== 'object') return `<span class="tree-val">${this.escapeHtml(String(nodes))}</span>`;

        const isArray = Array.isArray(nodes);
        let html = `<ul class="tree-node ${isArray ? 'tree-array' : 'tree-object'}">`;

        for (const [key, val] of Object.entries(nodes)) {
            html += '<li>';
            if (!isArray) html += `<strong class="tree-key">${this.escapeHtml(key)}:</strong> `;
            html += (typeof val === 'object' && val !== null) 
                ? this.renderTree(val) 
                : `<span class="tree-val">${this.escapeHtml(String(val))}</span>`;
            html += '</li>';
        }

        return html + '</ul>';
    },

    escapeHtml(str) {
        const div = document.createElement('div');
        div.textContent = str;
        return div.innerHTML;
    },

    // Core Status Updaters
    rag(data) {
        if (!this.elements.rag) return;

        let statusStr = 'OFFLINE';
        if (typeof data === 'string') {
            statusStr = data;
        } else if (data && typeof data === 'object') {
            statusStr = (data.status === 'online' || data.rag_service === 'online') ? 'online' : (data.status || 'offline');
        }

        const isOnline = (statusStr.toLowerCase() === 'online' || statusStr.toLowerCase() === 'success');
        this.elements.rag.innerText = isOnline ? 'ONLINE' : statusStr.toUpperCase();
        this.elements.rag.style.color = isOnline ? '#059669' : '#dc2626';
    },

    ollama(data) {
        if (!this.elements.ollama) return;

        let isOnline = false;
        if (data && typeof data === 'object') {
            isOnline = data.active === true || data.status === 'online';
        } else if (typeof data === 'string') {
            isOnline = data.toLowerCase() === 'online';
        }

        this.elements.ollama.innerText = isOnline ? 'ONLINE' : 'OFFLINE';
        this.elements.ollama.style.color = isOnline ? '#059669' : '#dc2626';
    },

    worker(data) {
        if (!this.elements.worker) return;

        let isOnline = false;
        if (data && typeof data === 'object') {
            isOnline = data.status === 'online' || data.active === true;
        } else if (typeof data === 'string') {
            isOnline = data.toLowerCase() === 'online';
        }

        this.elements.worker.innerText = isOnline ? 'ONLINE' : 'OFFLINE';
        this.elements.worker.style.color = isOnline ? '#059669' : '#dc2626';
    },

    models(models) {
        if (!this.elements.models) return;
        this.elements.models.innerHTML = (models && Array.isArray(models) && models.length > 0) 
            ? models.map(m => `<li>${this.escapeHtml(m.name || m)}</li>`).join('') 
            : '<li>No models detected</li>';
    },

    emails(status) { /* Placeholder for email queue status */ },
    async chat(userQuery) { /* Placeholder for chat logic */ }
};/** snapshots_controller.js */
const SnapshotController = {
    async displayForm() {

        const fields = { 
            'url': {}, 
            'description': {}, 
            'page': {} 
        };
        const form = document.getElementById('form');
        if (!form) return;
        
        // Clear the form and re-render only the fields
        form.innerHTML = '';
        Controller.eForm(form, fields);

        const btn = App.item('button');
        btn.type = 'button';
        btn.className = 'btn btn-outline-primary mt-2';
        btn.innerHTML = "Queue Email Task";
        form.appendChild(btn);

        btn.onclick = async (e) => {
            e.preventDefault();
            
            // Use the existing Controller utility to capture all form inputs
            // This assumes the fields match the keys in your SnapshotController.bindEmails schema
            const postData = {
                url: document.getElementById('url')?.value,
                description: document.getElementById('description')?.value,
                page: document.getElementById('page')?.value
            };

            App.spinner();

            try {
                const res = await fetch(App.url('ingestion/test'), {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(postData)
                });

                const result = await res.json();

                console.log(result);

                if (res.ok) {
                    App.flash('Success: Snapshot queued with ID ' + (result.id || 'N/A'));
                } else {
                    throw new Error(result.message || 'Server returned an error');
                }

                
            } catch (err) {
                App.flash('Error: ' + err.message);
                console.error('Snapshot POST error:', err);
            } finally {
                App.clearSpinner();
            }
        };
    },
};/** pentest_controller.js */
const PentestController = {};

PentestController.scan = async function() {
    try {
        App.spinner();
        const res = await fetch(App.url('pentest/scan/192.168.0.218'));
        const result = await res.json();

        if (res.ok) {
            App.flash('Success: scanned IP');
            this.display(result);
        } else {
            throw new Error(result.message || 'Server returned an error');
        }
    } catch (err) {
        App.flash('Error: ' + err.message);
    } finally {
        App.clearSpinner();
    }
};

PentestController.display = function(result) {
    const container = App.getItem('pentest');
    if (!container) return;

    container.innerHTML = '';

    for (let res in result) {

        
        // Bind the click event correctly
        const rowData = result[res];
        console.log(rowData);
        this.row(rowData,container);
    }
};

PentestController.row = function(rowData,container){

    for(let row in rowData){

        const tbl = App.item('table');

        tbl.setAttribute('class','tbl');

        const trOne = App.item('tr');

        const trTwo = App.item('tr');

        const trThree = App.item('tr');

        const trFour = App.item('tr');

        this.cell(rowData[row]['key'],trOne);

        this.cell(rowData[row]['value'],trOne);

        tbl.appendChild(trOne);

        this.cell('PORT',trTwo);

        this.cell(rowData[row]['port'],trTwo);

        tbl.appendChild(trTwo);

        this.cell('SERVICE',trThree);

        this.cell(rowData[row]['service'],trThree);

        tbl.appendChild(trThree);

        this.cell('RISK',trFour);

        this.cell(rowData[row]['risk'],trFour);

        tbl.appendChild(trFour);

        container.appendChild(tbl);

        console.log(rowData[row]);

    }

};

PentestController.cell = function(value,tr){

    const title = App.item('td');

    title.innerHTML = value;

    tr.appendChild(title);
};

PentestController.examine = async function(examine){

    App.flash('clicked: ' + examine);

};const PageRegistry = {
    'rag': () => RagController.bindRag(),
    'emails': () => Controller.bindEmails(),
    'agent': () => AgentController.bindAgents(),
    'docs': () => Controller.docs('docs'),
    'tiktok': () => TiktokController.bindPosts(),
    'agentemail': () => AgentController.bindAgentEmail(),
    'autoform': () => AgentController.autoForm(),
    'sales': () => SalesController.bindSales(),
    'snapshot': () => SnapshotController.displayForm(),
    'health': () => {
        HealthController.init();
        HealthController.get();
        HealthController.chat('Hello');
        HealthController.testSuite();
    },
    'pentest': () => PentestController.scan(),
    'agentic': () => AgenticController.init(),
    'mobile': () => MobileController.init()
};/**
 * Mobile Controller
 */
const MobileController = {
    init() {
        this.log('Initializing MobileController', 'MobileController:init', 'info');
        this.getRecords();
        this.openScreen('screen-home');
        this.bindEvents();
    },

    log(data, label = 'MobileController', level = 'log') {
        if (typeof App !== 'undefined' && App.debug) {
            App.debug(data, label, level);
        }
    },

    getUrl(endpoint) {
        return (typeof App !== 'undefined' && App.url) 
            ? App.url(endpoint) 
            : `/php/${endpoint}`;
    },

    bindEvents() {
        const agentList = document.getElementById('agentic-list');
        if (!agentList) {
            this.log('agentic-list container not found', 'MobileController:bindEvents', 'warn');
            return;
        }

        agentList.addEventListener('click', (e) => {
            const btn = e.target.closest('.btn-view-agent');
            if (!btn) return;

            const card = btn.closest('.job-card');
            if (!card) return;

            this.log('Agent view button clicked', 'MobileController:bindEvents', 'info');

            const title = card.dataset.title || '';
            const text = card.dataset.text || '';
            const ts = card.dataset.ts || '';
            let output = card.dataset.output || '';

            try {
                output = JSON.parse(output);
            } catch (_) {
                this.log('Output data is raw string, not JSON', 'MobileController:bindEvents', 'debug');
            }

            this.showDetail(title, text, ts, output);
        });
    },

    openScreen(screenId) {
        this.log(`Opening screen: #${screenId}`, 'MobileController:openScreen', 'info');
        document.querySelectorAll('#mobile .screen').forEach(s => s.classList.remove('active'));
        const target = document.getElementById(screenId);
        if (target) {
            target.classList.add('active');
        } else {
            this.log(`Target screen #${screenId} not found`, 'MobileController:openScreen', 'warn');
        }
    },

    showDetailLayout() {
        this.log('Step 1: Checking for existing #screen-detail', 'MobileController:showDetailLayout', 'debug');
        let screen = document.getElementById('screen-detail');
        if (screen) {
            this.log('Step 1a: Existing #screen-detail found in DOM, reusing instance', 'MobileController:showDetailLayout', 'info');
            return screen;
        }

        this.log('Step 2: Creating outer #screen-detail container', 'MobileController:showDetailLayout', 'debug');
        screen = document.createElement('div');
        screen.id = 'screen-detail';
        screen.className = 'screen';
        screen.setAttribute('role', 'region');
        screen.setAttribute('aria-label', 'Agent Detail Screen');

        this.log('Step 3: Building top navigation bar', 'MobileController:showDetailLayout', 'debug');
        const topbar = document.createElement('div');
        topbar.className = 'detail-topbar';

        const backBtn = document.createElement('button');
        backBtn.type = 'button';
        backBtn.className = 'btn btn-secondary';
        backBtn.setAttribute('aria-label', 'Go back to agent list');
        backBtn.textContent = '← Back';
        backBtn.onclick = () => this.openScreen('screen-agentic');

        const badge = document.createElement('span');
        badge.className = 'badge success';
        badge.textContent = 'Active';

        topbar.append(backBtn, badge);

        this.log('Step 4: Constructing detail card layout structure', 'MobileController:showDetailLayout', 'debug');
        const card = document.createElement('div');
        card.className = 'detail-card';

        const h2 = document.createElement('h2');
        h2.className = 'detail-title';

        const p = document.createElement('p');
        p.className = 'detail-summary';

        const outputBox = document.createElement('div');
        outputBox.className = 'detail-output-container';

        const small = document.createElement('small');
        small.className = 'detail-timestamp';

        card.append(h2, p, outputBox, small);
        screen.append(topbar, card);

        this.log('Step 5: Locating DOM placement target within #mobile frame', 'MobileController:showDetailLayout', 'debug');
        const phoneScreen = document.querySelector('#mobile .phone-screen');
        const navBar = phoneScreen?.querySelector('.nav-bar');

        if (navBar) {
            this.log('Step 5a: Inserting #screen-detail before .nav-bar', 'MobileController:showDetailLayout', 'info');
            phoneScreen.insertBefore(screen, navBar);
        } else if (phoneScreen) {
            this.log('Step 5b: Appending #screen-detail to .phone-screen', 'MobileController:showDetailLayout', 'info');
            phoneScreen.appendChild(screen);
        } else {
            this.log('Step 5c: Fallback appending #screen-detail to #mobile root', 'MobileController:showDetailLayout', 'warn');
            const mobileRoot = document.getElementById('mobile');
            if (mobileRoot) mobileRoot.appendChild(screen);
        }

        this.log('Step 6: Detail screen layout injection complete', 'MobileController:showDetailLayout', 'info');
        return screen;
    },

    createCardElement(title, category, text, ts, rawOutput) {
        const card = document.createElement('div');
        card.className = 'job-card';
        card.dataset.category = category;
        card.dataset.title = title;
        card.dataset.text = text;
        card.dataset.ts = ts;
        card.dataset.output = (typeof rawOutput === 'object' && rawOutput !== null) 
            ? JSON.stringify(rawOutput) 
            : String(rawOutput ?? '');

        const headerRow = document.createElement('div');
        headerRow.className = 'job-header-row';

        const h2 = document.createElement('h2');
        h2.textContent = title;

        const badge = document.createElement('span');
        badge.className = 'badge success';
        badge.textContent = 'Dispatched';

        headerRow.append(h2, badge);

        const company = document.createElement('h3');
        company.className = 'company-name';
        company.textContent = 'Sharpishly Agent ';

        const viaSpan = document.createElement('span');
        viaSpan.textContent = 'via Client Local';
        company.appendChild(viaSpan);

        const summary = document.createElement('p');
        summary.className = 'job-summary';
        summary.textContent = text;

        const footer = document.createElement('div');
        footer.className = 'job-footer';

        const timestamp = document.createElement('span');
        timestamp.className = 'timestamp';
        timestamp.textContent = `Created: ${ts}`;

        const btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'btn btn-primary btn-view-agent';
        btn.setAttribute('aria-label', `View details for ${title}`);
        btn.textContent = 'View Agent';

        footer.append(timestamp, btn);
        card.append(headerRow, company, summary, footer);
        
        return card;
    },

    async generateAgent() {
        const input = document.getElementById('agent-instruction');
        const instruction = input?.value.trim();

        if (!instruction) {
            this.log('Empty instruction submitted', 'MobileController:generateAgent', 'warn');
            return alert('Please enter an instruction message.');
        }

        try {
            const url = this.getUrl('mobile-agent-create');
            const response = await fetch(url, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ instruction })
            });

            const res = await response.json();

            if (res.status !== 'success' && !res.data) {
                return alert(res.error || 'Failed to dispatch agent plan.');
            }

            input.value = '';
            await this.getRecords();
            this.openScreen('screen-agentic');
        } catch (err) {
            this.log(err, 'MobileController:generateAgentException', 'error');
            alert('Failed to dispatch agent plan.');
        }
    },

    async getRecords() {
        try {
            const url = this.getUrl('mobile-agent');
            const response = await fetch(url);
            const res = await response.json();

            if (!res.records || !Array.isArray(res.records)) return;

            renderMobileAgents(res);
        } catch (err) {
            this.log(err, 'MobileController:fetchException', 'error');
        }
    },

    renderFormattedOutput(container, data) {
        container.textContent = '';
        this.log('Converting raw output via App.dBug', 'MobileController:renderOutput', 'debug');
        
        if (typeof App !== 'undefined' && typeof App.dBug === 'function') {
            const dBugNode = App.dBug(data);
            container.appendChild(dBugNode);
        } else {
            container.textContent = typeof data === 'object' ? JSON.stringify(data, null, 2) : String(data);
        }
    },

    showDetail(title, text, ts, output = '') {
        this.log('Populating data into detail screen', 'MobileController:showDetail', 'info');
        const screen = this.showDetailLayout();

        const titleEl = screen.querySelector('.detail-title');
        const summaryEl = screen.querySelector('.detail-summary');
        const tsEl = screen.querySelector('.detail-timestamp');
        const outputContainer = screen.querySelector('.detail-output-container');

        if (titleEl) {
            titleEl.textContent = title;
            this.log(`Title set: "${title}"`, 'MobileController:showDetail', 'debug');
        }
        if (summaryEl) {
            summaryEl.textContent = text;
            this.log('Summary populated', 'MobileController:showDetail', 'debug');
        }
        if (tsEl) {
            tsEl.textContent = ts;
            this.log(`Timestamp set: "${ts}"`, 'MobileController:showDetail', 'debug');
        }

        if (outputContainer) {
            this.log('Rendering dBug table layout into container', 'MobileController:showDetail', 'debug');
            this.renderFormattedOutput(outputContainer, output);
        }

        this.openScreen('screen-detail');
    }
};

/**
 * Renders a JSON payload of agent records into the mobile #agentic-list UI.
 */
function renderMobileAgents(payload) {
    const agentList = document.getElementById('agentic-list');
    if (!agentList) return;

    if (!payload?.records || !Array.isArray(payload.records)) {
        agentList.textContent = '';
        return;
    }

    agentList.textContent = '';

    payload.records.forEach(item => {
        renderMobileAgentItem(item);
    });
}

/**
 * Renders a single agent object into a temporary card and appends to #agentic-list.
 */
function renderMobileAgentItem(item) {
    const agentList = document.getElementById('agentic-list');
    if (!agentList) return;

    const title = item.agent_name || item.title || 'Sharpishly Agent';
    const category = item.role || item.category || 'career';
    const text = item.description || item.message || item.summary || '';
    const ts = item.created_at || '';
    const rawOutput =
        item.output ??
        item.result ??
        item.parsed ??
        item.instruction ??
        item.prompt ??
        '';

    const card = MobileController.createCardElement(title, category, text, ts, rawOutput);
    agentList.appendChild(card);
}const HomeController = {
    steps: [
        ['sudoers', 'maxie-setup-sudoers'],
        ['app',     'maxie-deploy-sharpishly'],
        ['ollama',  'maxie-prep-ollama'],
        ['health',  'maxie-health-check']
    ],

    async deploy() {
        const btn = document.getElementById('btn-trigger-deploy');
        if (btn) btn.disabled = true;

        for (const [id, alias] of this.steps) {
            this.setStatus(id, 'running');

            try {
                const res = await fetch(`/php/terminal/load/${encodeURIComponent(alias)}`);

                if (!res.ok) {
                    this.setStatus(id, 'failed');
                    break;
                }
                this.setStatus(id, 'done');
            } catch {
                this.setStatus(id, 'failed');
                break;
            }
        }

        if (btn) btn.disabled = false;
    },

    setStatus(id, status) {
        const bar = document.getElementById(`bar-${id}`);
        const badge = document.getElementById(`badge-${id}`);

        const config = {
            running: { width: '50%',  bar: 'progress-bar progress-bar-striped progress-bar-animated bg-primary', badge: 'badge bg-warning', text: 'Running...' },
            done:    { width: '100%', bar: 'progress-bar bg-success', badge: 'badge bg-success', text: 'Complete' },
            failed:  { width: '100%', bar: 'progress-bar bg-danger',  badge: 'badge bg-danger',  text: 'Failed' }
        }[status];

        if (bar)   { bar.style.width = config.width; bar.className = config.bar; }
        if (badge) { badge.className = config.badge; badge.textContent = config.text; }
    }
};/** model.js */

/**
 * Model: Global App State
 */
const Model = {
    queue: [],
    healthStatus: null,
    currentPage: 'home'
};




/** view.js */
/**
 * View: Global App State
 */
const view = {
    neuralPipeline() {
        const container = document.getElementById('neural-pipeline');
        if (!container) return;

        // Clear existing content
        container.innerHTML = '';

        // Create the wrapper
        const np = App.item('div');
        np.className = 'pipeline-list';

        // Map your Model.queue to UI elements
        Model.queue.forEach(item => {
            const row = App.item('div');
            row.className = 'card mb-2 p-2 small border-0 shadow-sm';
            row.innerHTML = `
                <div class="d-flex justify-content-between">
                    <strong>${item.name}</strong>
                    <span class="text-primary">${item.status}</span>
                </div>
            `;
            np.appendChild(row);
        });

        // Append to the target
        container.appendChild(np);
    }
};


document.addEventListener('DOMContentLoaded', () => Controller.init());

/* Lightweight replacement for Bootstrap's Collapse JS */
document.addEventListener('click', (e) => {

    // Handle Navbar Toggler
    if (e.target.matches('.navbar-toggler')) {
        document.querySelector('.nav-menu').classList.toggle('show');
    }

    const toggle = e.target.closest('[data-bs-toggle="collapse"]');
    if (toggle) {
        const targetSelector = toggle.getAttribute('data-bs-target');
        const target = document.querySelector(targetSelector);
        if (target) {
            target.classList.toggle('show');
        }
    }
});
