/** Auto-generated by build.sh **/
/**
 * App: Global Utilities & Template Engine
 */
const App = {
    async loadTemplate(url, data = {}) {
        try {
            const res = await fetch(url);
            if (!res.ok) throw new Error(`Missing: ${url}`);
            let template = await res.text();
            
            // Recursive path resolver for {{ object.key }}
            return template.replace(/{{\s*([\w.]+)\s*}}/g, (_, path) => {
                const value = path.split('.').reduce((obj, key) => obj?.[key], data);
                if (typeof value === 'boolean') return value ? '<span class="text-success">ONLINE</span>' : '<span class="text-danger">OFFLINE</span>';
                return value ?? '';
            });
        } catch (e) {
            return `<div class="p-4 text-danger">Template Error: ${e.message}</div>`;
        }
    },
    crm() { Model.currentPage = 'home'; Controller.render(); },
    cyberdeck() { Model.currentPage = 'llm'; Controller.render(); },
    url(path) { 
    	// Ensure the path does not start with a / to avoid double slashes
    	const cleanPath = path.startsWith('/') ? path.substring(1) : path;
    	return `${window.location.origin}/php/${cleanPath}`; 
    },
    selectList(fields, callback) {
    const select = document.createElement('select');
    select.className = 'agent-selector'; // For CSS styling

    // Add a default placeholder
    const defaultOption = document.createElement('option');
    defaultOption.text = 'Select an agent...';
    defaultOption.value = '';
    select.appendChild(defaultOption);

    // Build the fields
    fields.forEach(field => {
        const option = document.createElement('option');
        option.value = field.id;
        option.text = field.name;
        select.appendChild(option);
    });

    // Use onchange for select elements
    select.onchange = function(e) {
        if (this.value) {
            callback(this.value);
        }
    };

    return select;
    },
    getApp() { return document.getElementById('app'); },
    item(e) { return document.createElement(e); },
    flash(msg) {
        const flash = document.getElementById('flash');
        if (!flash) return;
        const alert = App.item('div');
        alert.style.cssText = 'width:100%;border-radius:16px;margin-bottom:10px;padding-top:10px;padding-bottom:10px;background-color:#ccc;text-align:center';
        alert.innerHTML = msg;
        flash.appendChild(alert);
    },
    getItem(e){return document.getElementById(e)},
};



// Add this helper to App
App.addAgentActions = function(form) {
    // Only proceed if we are in agent context
    const agentId = document.getElementById('agent_id');
    if (!agentId || !agentId.value) return;

    const actions = [
        "Deploy latest container", "Rotate SSH keys", "Scale worker nodes", 
        "Execute maintenance script", "Clear orphaned containers", 
        "Backup database volume", "Audit security logs", "Restart Nginx", 
        "Purge temporary files", "Verify integrity"
    ];

    const label = App.item('label');
    label.innerHTML = "Agent Task Actions";
    form.appendChild(label);

    const select = document.createElement('select');
    select.className = 'form-control mb-2';
    select.innerHTML = '<option value="">-- Choose an action --</option>';

    actions.forEach(action => {
        const opt = document.createElement('option');
        opt.value = action;
        opt.text = action;
        select.appendChild(opt);
    });

    select.onchange = (e) => {
        if (e.target.value) {
            const body = document.getElementById('body');
            body.value += (body.value ? "\n" : "") + `Action: ${e.target.value}`;
        }
    };
    form.appendChild(select);
};

App.agentEmailForm = function(agent) {
    // 1. Navigate to the email page
    Controller.navigate('emails');

    // 2. Wait for the form to be rendered by the router
    setTimeout(() => {
        const form = document.getElementById('form');
        const subject = document.getElementById('subject');

        if (subject) {
            subject.value = `Task for: ${agent.agent_name}`;
        }

        // 3. Add hidden agent context to associate the task
        const hidden = document.createElement('input');
        hidden.type = 'hidden';
        hidden.id = 'agent_id';
        hidden.value = agent.id;
        form.appendChild(hidden);

        // 4. Inject agent-specific form options/metadata
        const info = document.createElement('div');
        info.className = 'mt-2 p-2 border bg-light';
        info.innerHTML = `<strong>Agent Context:</strong> ${agent.role} active.`;
        form.appendChild(info);

        App.flash(`Agent ${agent.agent_name} loaded into email form.`);
    }, 100);
};
App.eForm = function(form, schema) {
    form.innerHTML = '';
    Object.keys(schema).forEach(key => {
        const field = schema[key];
        const id = field.id || key;
        const type = field.type || 'text';
        
        // Create element: Textarea if defined, else input
        const el = App.item(type === 'textarea' ? 'textarea' : 'input');
        el.id = id;
        el.className = 'form-control';
        
        if (field.placeholder) el.placeholder = field.placeholder;
        if (type !== 'textarea') el.type = type;

        const label = App.item('label');
        label.className = 'form-label fw-bold';
        label.textContent = key.charAt(0).toUpperCase() + key.slice(1);
        
        const row = App.item('div');
        row.className = 'mb-3';
        row.appendChild(label);
        row.appendChild(el);
        form.appendChild(row);
    });
};

App.log = function(log){
    console.log(log);
};/* app_spinner.js */
App.spinner = function(){
    const spinner = document.getElementById('spinner');
    if (spinner) spinner.style.display = 'flex'; // Make it visible
};

App.clearSpinner = function(){
    const spinner = document.getElementById('spinner');
    if (spinner) spinner.style.display = 'none'; // Hide it again
};/** app_modal.js */
App.modal = {
    open(content, options = {}) {
        const {
            closeOnBackdrop = true,
            closeOnEscape = true,
            className = '',
            id = ''
        } = options;

        // Create elements
        const overlay = document.createElement('div');
        overlay.id = 'app-modal-overlay';
        overlay.className = 'app-modal-overlay'; // Managed by CSS

        const modal = document.createElement('div');
        modal.className = `modal-content ${className}`; // Managed by CSS
        modal.innerHTML = content;
        if (id) modal.id = id;
        

        overlay.appendChild(modal);
        document.body.appendChild(overlay);

        // Event management
        if (closeOnBackdrop) {
            overlay.onclick = (e) => {
                if (e.target === overlay) this.close();
            };
        }

        if (closeOnEscape) {
            const onKey = (e) => { if (e.key === 'Escape') this.close(); };
            document.addEventListener('keydown', onKey);
            overlay._modalKeyHandler = onKey;
        }
    },
    
    close() {
        const overlay = document.getElementById('app-modal-overlay');
        if (!overlay) return;
        
        if (overlay._modalKeyHandler) {
            document.removeEventListener('keydown', overlay._modalKeyHandler);
        }
        overlay.remove();
    }
};/**
 * TikTok Controller: UX Enhanced
 */
const TiktokController = {
    async bindPosts() {
        // App.loadView (if needed) - assumes HTML is already injected
        const btn = document.getElementById('tiktok-submit');
        const contentInput = document.getElementById('tiktok-content');

        if (!btn || !contentInput) return;

        btn.onclick = (e) => {
            // Visual feedback: brief pulse
            btn.style.opacity = '0.5';
            setTimeout(() => btn.style.opacity = '1', 200);

            AgentController.tiktokPost(contentInput.value);
        };
    }
};
/**
 * Agent Controller
 */
const AgentController = {
    // Add to your existing AgentController object
    tiktokPost: function(content) {
    if (!content.trim()) {
        App.flash('Please enter some content first.');
        return;
    }

    const dialog = App.item('div');
    dialog.className = 'border p-3 mt-3 bg-warning';
    dialog.innerHTML = `
        <h5>Confirm TikTok Post</h5>
        <p>Posting: <em>${content}</em></p>
        <button id="tiktok-confirm" type="button" class="btn btn-dark">Confirm & Post</button>
    `;
    
    // Mount within the app container for consistent styling
    const host = document.getElementById('app') || document.body;
    host.appendChild(dialog);

    document.getElementById('tiktok-confirm').onclick = () => {
        // Dummy API Response Logic
        const mockResponse = { status: 'success', id: 'tt_' + Math.random().toString(36).substr(2, 9) };
        
        App.flash('TikTok post queued: ' + mockResponse.id);
        dialog.remove();
        
        // Clear input after success
        const contentInput = document.getElementById('tiktok-content');
        if (contentInput) contentInput.value = '';
    };
},
// Note the 'async' keyword here
async bindAgentsDefault(){
    const form = App.getItem('form');
    
    // Await the result so it resolves to the actual HTML string
    const html = await App.loadTemplate('views/pages/welcome.html', {'foo':'bar'});
    
    // Now you have the string, not the Promise
    form.innerHTML = html;
},
    async bindAgents() {
        this.bindAgentsDefault();
        const fields = { 'create': {}, 'read': {}};
        const menu = document.getElementById('menu');
        if (menu) Controller.menuFields(fields, menu);
    },
    contacts: function(form) {
        const container = App.item('div');
        container.id = 'agent-contacts-container';
        container.className = 'mt-3 p-2 border';
        
        // 1. Add Title first
        const title = App.item('h5');
        title.innerHTML = 'Available Contacts';
        container.appendChild(title);

        // 2. Populate contacts inside the container
        this.address(container);
        
        form.appendChild(container);
        return container;
    },

    address: function(container) {
        const contacts = [
            { name: "Admin", email: "admin@system.local" },
            { name: "DevOps", email: "devops@system.local" }
        ];

        contacts.forEach(c => {
            const btn = App.item('button');
            btn.className = 'btn btn-sm btn-secondary m-1';
            btn.innerHTML = c.name;
            
            // Set the 'to' field when clicked
            btn.onclick = (e) => {
                e.preventDefault();
                const toField = document.getElementById('to');
                if (toField) toField.value = c.email;
            };
            
            container.appendChild(btn);
        });
    },
    // Add to Controller object
    async displayAgentRecords(form) {
        form.innerHTML = '<h3>Active Agents</h3>';
        
        // Fetch existing agents
        try {
            const res = await fetch(App.url('agent/index')); // Assumes your AgentController exists
            const agents = await res.json();
            console.log(agents);
            const table = App.item('table');
            table.className = 'agent-table';
            table.innerHTML = `<thead><tr><th>Name</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead>`;
            const tbody = App.item('tbody');

            agents.forEach(agent => {
        const tr = App.item('tr');
        
        // Define your actions
        const actions = [
            {id: 'autoform', name: 'Automatic Form Completion'},
            {id: 'snapshot', name: 'Ingestion external form'},
            {id: 'tiktok', name: 'Tiktok'},
            {id: 'pentest',name: 'Penetration Testing'},
            {id: 'pension',name: 'Pension Schemes'},
        ];

        // Build standard cells using template literals for safe, static content
        tr.innerHTML = `
            <td>${agent.agent_name}</td>
            <td>${agent.role}</td>
            <td><span class="badge ${agent.status}">${agent.status}</span></td>
        `;

        // Create the select cell
        const actionTd = document.createElement('td');
        const select = App.selectList(actions, (actionId) => {

        // TODO: Create loop
        // pages [{}];

        if (actionId === 'snapshot') {

            Controller.navigate(actionId);

        } else if (actionId === 'pentest') {

            Controller.navigate(actionId);

        } else if (actionId === 'autoform') {

            Controller.navigate(actionId );

        } else  if (actionId === 'tiktok') {

            Controller.navigate(actionId );

        } else if (actionId === 'email') {

            Controller.navigate(actionId );

        } else {
            // Handle other actions (start, stop, etc.)
            console.log(`Action ${actionId} selected for agent ${agent.agent_name}`);
        }

        });
        
        actionTd.appendChild(select);
        tr.appendChild(actionTd);
        
        tbody.appendChild(tr);
    });
            table.appendChild(tbody);
            form.appendChild(table);
        } catch (e) {
            form.innerHTML += '<p>No agents found or error loading.</p>';
        }
    },
};

AgentController.bindAgentEmail = function() {
    const container = document.getElementById('email-fields');
    const sendRow = document.getElementById('send-button');
    if (!container || !sendRow) return;

    // Schema: Keys are labels, Values contain technical attributes
    const schema = { 
        'email': { 'id': 'to', 'placeholder': 'recipient@example.com' }, 
        'title':  { 'id': 'subject', 'placeholder': 'Subject line' }, 
        'content': { 'id': 'message', 'type': 'textarea', 'placeholder': 'Email body...' } 
    };

    App.eForm(container, schema);

    if (!document.getElementById('send-btn')) {
        const btn = App.item('button');
        btn.id = 'send-btn';
        btn.type = 'button';
        btn.className = 'btn btn-primary';
        btn.innerHTML = 'Queue Email Task';
        
        btn.onclick = () => {
            // Correctly targeting the IDs generated by App.eForm
            AgentController.emailQueue(
                document.getElementById('to'),
                document.getElementById('subject'),
                document.getElementById('message')
            );
        };
        sendRow.appendChild(btn);
    }
};

AgentController.emailQueue = function(toInput, subjectInput, bodyInput) {
    // 1. Basic validation
    if (!toInput.value || !toInput.value.includes('@')) {
        App.flash('Please enter a valid email address.');
        return;
    }

    const btn = document.getElementById('send-btn');
    if (btn) btn.disabled = true; // Disable button to prevent double-submit

    const payload = {
        email: toInput.value.trim(),
        title: subjectInput.value.trim(),
        content: bodyInput.value.trim(),
        status: 'waiting'
    };

    const uniqueId = 'email_' + Date.now().toString(36) + '_' + Math.random().toString(36).substr(2, 5);

    fetch(App.url(`emails/queue/${uniqueId}`), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
    })
    .then(res => res.json())
    .then(result => {
        if (result.status === 'success') {
            App.flash('Successfully queued: ' + result.id);
            toInput.value = '';
            subjectInput.value = '';
            bodyInput.value = '';
        } else {
            App.flash('Error: ' + (result.message || 'Persistence failure'));
        }
    })
    .catch(err => {
        App.flash('Connection error: ' + err.message);
    })
    .finally(() => {
        if (btn) btn.disabled = false; // Re-enable button
    });
};

AgentController.tiktokPost = function(content) {
    if (!content.trim()) {
        App.flash('The feed is empty! Give us something viral.');
        return;
    }

    const dialog = App.item('div');
    dialog.className = 'card mt-4 p-4 border-2 border-danger'; // High-visibility border
    dialog.innerHTML = `
        <h5 style="color: #dc3545;">⚠️ Broadcast Authorization</h5>
        <p>You are about to launch this content to TikTok:</p>
        <div class="p-3 bg-light border mb-3"><em>"${content}"</em></div>
        <button id="tiktok-confirm" class="btn btn-outline-primary mt-2" style="width: 100%;">
            CONFIRM & LAUNCH
        </button>
    `;
    
    const host = document.getElementById('app');
    host.appendChild(dialog);

    document.getElementById('tiktok-confirm').onclick = () => {
        const mockResponse = { status: 'success', id: 'viral_' + Math.random().toString(36).substr(2, 5) };
        
        App.flash('🚀 Posted to TikTok: ' + mockResponse.id);
        dialog.remove();
        document.getElementById('tiktok-content').value = '';
    };
};

AgentController.autoForm = function() {
    const container = App.getItem('autoform-container');
    container.innerHTML = '<h3>Automatic Form Completion</h3>';

    // Create a form container
    const form = App.item('div');
    form.id = 'autoform-container';
    container.appendChild(form);

    // Schema for target platforms
    const schema = {
        'Job Source': { 'id': 'source', 'placeholder': 'e.g., jobs.com' },
        'Role': { 'id': 'role', 'placeholder': 'Software Developer' },
        'Experience': { 'id': 'exp', 'placeholder': 'Years of experience' }
    };

    // Use App.eForm to build the interface
    App.eForm(form, schema);

    // Add Submit Action
    const btn = App.item('button');
    btn.className = 'btn btn-primary mt-3';
    btn.innerHTML = 'Execute Auto-Fill';
    btn.onclick = () => {
        const data = {
            source: document.getElementById('source').value,
            role: document.getElementById('role').value,
            exp: document.getElementById('exp').value
        };
        App.flash('Initiating auto-form completion for ' + data.source);
        console.log('Payload:', data);
    };
    
    form.appendChild(btn);
    const url = 'ingestion/save/?url=https://www.applybe.com/?a=145F80311.0';
    AgentController.formPreview(url);
};

// Ensure 'async' is present to use 'await'
AgentController.formPreview = async function(url) {
    const preview = document.getElementById('preview');
    if (!preview) return; // Guard clause

    App.spinner();
    try {
        const response = await fetch(App.url(url));
        if (!response.ok) throw new Error('Failed to fetch preview');
        
        const html = await response.text();
        preview.innerHTML = html;
    } catch (e) {
        // Corrected from e.getMessage() to e.message
        App.flash('Error: ' + e.message);
    } finally {
        App.clearSpinner();
    }
};/**
 * Agentic Controller
 */
const AgenticController = {
    init() {
        const data = {foo: 'bar',app: App};
        console.log(data);
    }
};

/** controllers.js **/

/**
 * Home Controller
 */
const HomeController = {};

/**
 * Rag Controller
 */
const RagController = {
        async bindRag() {
        const btn = document.getElementById('rag-send');
        const input = document.getElementById('rag-input');
        const history = document.getElementById('chat-history');
        if (!btn) return;

        btn.onclick = async () => {
            const query = input.value.trim();
            if (!query) return;
            history.innerHTML += `<p><strong>You:</strong> ${query}</p>`;
            input.value = '';
            
            App.spinner(); // Minimal change: Start spinner
            
            try {
                // Changed from POST/body to GET/URL query parameter
                const url = App.url('rag/rag/') + encodeURIComponent(query);
                const res = await fetch(url, {
                    method: 'GET'
                });
                const data = await res.json();
                history.innerHTML += `<p><strong>Bot:</strong> ${data.answer || data.message}</p>`;
            } catch (e) { history.innerHTML += `<p class="text-danger">Error: Service unavailable</p>`; }
            finally {
                App.clearSpinner(); // Minimal change: Stop spinner
            }
            
            history.scrollTop = history.scrollHeight;
        };
    },
};

/**
 * Llm Controller
 */
const LlmController = {};


/**
 * Docs Controller
 */
const DocsController = {};

/**
 * Sales Controller
 */
const SalesController = {
    async bindSales() {
        // 1. Load the page shell into the app container
        const target = document.getElementById('app');
        target.innerHTML = await App.loadTemplate('/views/sales/index.html');

        // 2. Now that the HTML is in the DOM, fetch and render the data
        const salesContainer = document.getElementById('sales-list');
        try {
            const res = await fetch(App.url('/views/sales/leads')); 
            const sales = await res.json();
            
            salesContainer.innerHTML = sales.map(s => `
                <tr>
                    <td>${s.company}</td>
                    <td>${s.tier}</td>
                    <td>${s.status}</td>
                    <td><button class="btn btn-sm btn-outline-info">Edit</button></td>
                </tr>
            `).join('');
        } catch (e) {
            salesContainer.innerHTML = '<tr><td colspan="4">Error loading data.</td></tr>';
        }
    }
};

/**
 * Leads Controller: Manages lead intake and feedback
 */
const LeadsController = {
    async loadLeads() {
        const feed = document.getElementById('leads-feed');
        if (!feed) return;
        try {
            const res = await fetch(App.url('lead/index'));
            const data = await res.json();
            feed.innerHTML = data.map(l => `
                <div class="list-group-item">
                    <strong>${l.name || 'Anonymous'}</strong>: ${l.notes}
                </div>
            `).join('');
        } catch (e) {
            feed.innerHTML = '<div class="text-danger">Error loading leads.</div>';
        }
    },

    async saveLead(formData) {
        const payload = Object.fromEntries(formData);
        await fetch(App.url('lead/log'), {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });
        this.loadLeads(); // Refresh after save
    }
};




/**
 * Controller: Orchestrates UI logic, data fetching, and event binding
 */
const Controller = {
    async autoFill() {
        const input = document.getElementById('autocomplete');
        if (!input) return;
        const ul = document.createElement('ul');
        const li = document.createElement('li');
        li.innerHTML = "test";
        ul.appendChild(li);
        input.appendChild(ul);
    },



    eFields(fields) {
        let post = {};
        for (let field in fields) {
            const el = document.getElementById(field);
            post[field] = el ? el.value : '';
        }
        return post;
    },

    eForm(form, fields) {
        for (let field in fields) {
            const input = App.item('input');
            input.setAttribute('id', field);
            const label = App.item('label');
            label.innerHTML = field;
            const row = App.item('div');
            row.appendChild(label);
            row.appendChild(input);
            form.appendChild(row);
        }
    },

    async bindEmails() {
    const fields = { 'to': {}, 'subject': {}, 'body': {} };
    const form = document.getElementById('form');
    if (!form) return;
    
    // Clear the form and re-render only the fields
    form.innerHTML = '';
    this.eForm(form, fields);

    const btn = App.item('button');
    btn.type = 'button';
    btn.className = 'btn btn-outline-primary mt-2';
    btn.innerHTML = "Queue Email Task";
    form.appendChild(btn);

    btn.onclick = (e) => {
        e.preventDefault();
        
        const toInput = document.getElementById('to');
        const subjectInput = document.getElementById('subject');
        const bodyInput = document.getElementById('body');
        
        // Use the reverted, clean emailQueue
        AgentController.emailQueue(toInput, subjectInput, bodyInput);
    };
},






async menuFields(fields, menu) {
    for (let field in fields) {
        let item = App.item('div');
        item.innerHTML = field;
        item.id = field;
        item.classList.add('menu-item'); // Use the CSS class
        
        item.onclick = async () => {
            let form = document.getElementById('form');
            if (!form) return;

            // Clear current form if necessary or reset state
            this.handleMenuClick(field, form);
        };
        menu.appendChild(item);
    }
},

// Controller method to handle the logic switch
handleMenuClick(field, form) {
    switch(field) {
        case 'create':
            this.createAgent(form);
            break;
        case 'read':
            AgentController.displayAgentRecords(form);
            break;
        case 'delete':
            let msg = App.item('div');
            msg.innerHTML = "Create a new agent to do the tasks you avoid";
            form.appendChild(msg);
            break;
    }
},

    // Triggered by the 'create' menu item
    createAgent(form) {
        // 1. Clear existing form content
        form.innerHTML = '';
        
        // 2. Define fields for the agent creation
        const fields = { 
            'agent_name': {}, 
            'description': {}, 
            'role': {} 
        };
        
        // 3. Populate form using your existing helper
        this.createAgentForm(form, fields);
        
        // 4. Add a submit button
        const btn = App.item('div');
        btn.style.cssText = 'cursor:pointer;border:1px dashed #ccc; margin-top: 10px; padding: 5px;';
        btn.innerHTML = "Save Agent";
	// 5. Post form data
        btn.onclick = async () => {
            const postData = this.eFields(fields);
            try {
                const res = await fetch(App.url('agent/test/'), {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(postData)
                });
                const data = await res.json();
                App.flash('Success id:' + data.id + ' created');
            } catch (e) { App.flash('Error'); }
        };

	//
        form.appendChild(btn);
    },

    // Handles looping through fields and injecting them into the form
    createAgentForm(form, fields) {
        // Reuse your existing logic, or use eForm if it matches perfectly
        this.eForm(form, fields);
    },    
    async init() {
        const host = window.location.hostname;
        const sub = host.split('.')[0];
        try {
            const res = await fetch('views/layouts/header.html');
            if (res.ok) {
                let headerTemplate = await res.text();
                const initialH1 = (sub === 'cyberdeck') ? 'Cyberdeck (LLM)' : 'Thomasons V3';
                document.getElementById('header').innerHTML = headerTemplate.replace(/{{\s*h1\s*}}/g, initialH1);
            }
        } catch (e) { console.error("Layout Engine init failed:", e); }

        // Trigger cookie consent immediately after init
        this.showCookieConsent();

        if (sub === 'crm') App.crm();
        else if (sub === 'cyberdeck') App.cyberdeck();
        else this.navigate('home');

        document.addEventListener('click', (e) => {
            const page = e.target.closest('[data-page]')?.dataset.page;
            if (page) { e.preventDefault(); this.navigate(page); }
        });
        App.spinner();
        App.clearSpinner();
    },

    showCookieConsent() {
        App.modal.open(`
            <h3>Cookie Policy</h3>
            <p>We use cookies to enhance your neural-pipeline experience. Do you accept our terms?</p>
            <div style="display:flex; gap:10px; justify-content:end; margin-top:20px;">
                <button id="btn-reject" class="btn btn-outline-secondary">Reject</button>
                <button id="btn-accept" class="btn btn-primary">Accept</button>
            </div>
        `, { closeOnBackdrop: false, closeOnEscape: false });

        document.getElementById('btn-accept').onclick = () => {
            console.log("Cookies accepted");
            App.modal.close();
        };

        document.getElementById('btn-reject').onclick = () => {
            console.log("Cookies rejected");
            App.modal.close();
        };
    },

    async render() {
        const target = document.getElementById('app');
        if (!target) return;

        const templatePath = Model.currentPage === 'home' 
            ? 'views/home/index.html' 
            : `views/pages/${Model.currentPage}.html`;

        let html = await App.loadTemplate(templatePath, {
            health: Model.healthStatus,
            queue: Model.queue
        });

        const headerH1 = document.querySelector('#header h1');
        if (headerH1) headerH1.textContent = Model.currentPage === 'home' ? 'Thomasons V3' : Model.currentPage.toUpperCase();
        
        document.querySelectorAll('.navbar .nav-link').forEach(link => {
            link.classList.toggle('active', link.dataset.page === Model.currentPage);
        });

        if (Model.currentPage === 'llm') {
            const itemsHtml = Model.queue.map(item => `
                <div class="card mb-2 p-2 small border-0 shadow-sm">
                    <div class="d-flex justify-content-between">
                        <strong>${item.name}</strong>
                        <span class="text-primary">${item.status}</span>
                    </div>
                </div>
            `).join('');
            html = html.replace('{{ queueHtml }}', itemsHtml || '<p class="text-muted small">No active jobs.</p>');
        }

        target.innerHTML = `<div class="fade-in">${html}</div>`;
        this.bindEvents();
        if (PageRegistry[Model.currentPage]) PageRegistry[Model.currentPage]();
    },

    navigate(page) { 
        
        const debug = {page: page};

        console.log(debug);
        
        Model.currentPage = page; this.render(); 

    },

    bindEvents() {
        const drop = document.getElementById('dropzone');
        const input = document.getElementById('fileInput');
        if (!drop || !input) return;

        drop.onclick = () => input.click();
        input.onchange = (e) => this.handleUpload(e.target.files);
        drop.ondragover = (e) => { e.preventDefault(); drop.style.backgroundColor = '#f0f7ff'; };
        drop.ondragleave = () => drop.style.backgroundColor = '';
        drop.ondrop = (e) => {
            e.preventDefault();
            drop.style.backgroundColor = '';
            this.handleUpload(e.dataTransfer.files);
        };
    },

    async handleUpload(files) {
        if (!files.length) return;
        const formData = new FormData();
        Array.from(files).forEach(f => {
            formData.append('documents[]', f);
            Model.queue.push({ name: f.name, status: 'processing', progress: 25 });
        });
        this.render();

        // Call the view update
        view.neuralPipeline();

        try {
            const res = await fetch(App.url('job/create'), { method: 'POST', body: formData });
            const result = await res.json(); // Capture the server response

            if (result.status === 'success') {
                Model.queue.forEach(item => { item.status = 'queued'; item.progress = 50; });
                this.render();

                // Hook into the JobProgressController for background monitoring
                JobProgressController.monitor(
                    result.job_id, 
                    (data) => {
                        App.flash("Pipeline Complete: " + data.message);
                        // Optional: Trigger a UI refresh to show the file as "processed"
                    },
                    (err) => {
                        App.flash("Pipeline Error: " + err.message);
                    }
                );
            }
        } catch (e) { 
            console.error("Upload failed", e);
            App.flash("Upload failed: Check network connection.");
        }
    },

    docsBindMessage(record, ul) {
        let li = document.createElement('li');
        li.innerHTML = '<b>You</b>:&nbsp;' + record.message;
        ul.appendChild(li);
    },
    docsBindAnswer(record, ul) {
        let li = document.createElement('li');
        li.innerHTML = '<b>Sharpishly</b>:&nbsp;' + record.answer;
        ul.appendChild(li);
    },
    async docs(page) {
        try {
            const res = await fetch(App.url('docs'));
            const data = await res.json();
            const target = document.getElementById('app');
            let ul = document.createElement('ul');
	    ul.setAttribute('id','docs');
            for (let id in data.records) {
                this.docsBindMessage(data.records[id], ul);
                this.docsBindAnswer(data.records[id], ul);
            }
            if (target) target.appendChild(ul);
        } catch (e) { }
    }
};
const JobProgressController = {
    monitor: function(jobId, onComplete, onError) {
        const interval = setInterval(async () => {
            try {
                const response = await fetch(`/php/job/status/${jobId}`);
                const data = await response.json();
                
                // 1. Update the UI directly
                const pipelineDiv = document.getElementById('neural-pipeline');
                if (pipelineDiv) {
                    pipelineDiv.innerHTML = `
                        <div class="alert alert-info">
                            Job #${jobId} status: <strong>${data.state}</strong>
                        </div>
                    `;
                }

                // 2. Lifecycle management
                if (data.state === 'completed') {
                    clearInterval(interval);
                    onComplete(data);
                } else if (data.state === 'failed') {
                    clearInterval(interval);
                    onError(data);
                }
            } catch (error) {
                console.error("Polling error:", error);
                clearInterval(interval);
            }
        }, 2000);
    }
};/** * HealthController: Orchestrates the Health Center UI
 * Pattern: Defensive DOM initialization + Robust Payload Handling
 */
const HealthController = {
    elements: {},

    // Ensure DOM elements are only mApped once, when they exist
    init() {
        this.elements = {
            rag: App.getItem('status-rag'),
            worker: App.getItem('status-worker'),
            ollama: App.getItem('status-ollama'),
            models: App.getItem('status-models')
        };
    },

// Inside HealthController.get()
async get() {
    if (Object.keys(this.elements).length === 0) this.init();
    
    App.spinner();
    try {
        const res = await fetch(App.url('health'));
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        
        const data = await res.json();

        // Normalizing data from the successful response
        this.rag(data.rag_service || 'offline');
        // ... (rest of your calls)

    } catch (e) {
        console.error("Health Center unreachable:", e);
        // Explicitly update the UI to show the service is unreachable
        this.rag('unreachable'); 
        App.flash(`Health Center Error: Service unreachable`);
    } finally {
        App.clearSpinner();
    }
},

    async rag() {
        if (!this.elements.rag) return;

        try {
            // Fetch the status from the new RagController endpoint
            const response = await fetch(App.url('rag/check'));
            const data = await response.json();

            // Determine if the service is online based on the API response
            const isOnline = (data.rag_service === 'online');

            // Update DOM
            this.elements.rag.innerText = isOnline ? 'ONLINE' : 'UNREACHABLE';
            this.elements.rag.style.color = isOnline ? '#28a745' : '#dc3545';
            
        } catch (e) {
            // Handle network or parsing errors
            console.error("RAG status check failed:", e);
            this.elements.rag.innerText = 'UNREACHABLE';
            this.elements.rag.style.color = '#dc3545';
            App.flash('RAG Service: Unreachable');
        }
    },

    ollama(data) {
        if (!this.elements.ollama) return;
        // Handle cases where data might be undefined
        const active = data?.active === true;
        this.elements.ollama.innerText = active ? 'ONLINE' : 'OFFLINE';
        this.elements.ollama.style.color = active ? '#28a745' : '#dc3545';
    },

    models(models) {
        if (!this.elements.models) return;
        this.elements.models.innerHTML = (models && models.length > 0) 
            ? models.map(m => `<li>${m.name}</li>`).join('') 
            : '<li>No models detected</li>';
    },

    worker(status) { /* Placeholder for worker-specific logic */ },

    emails(status) { /* Placeholder for email-queue logic */ },

    async chat(userQuery) { /* Placeholder for chat logic */}

};/** snapshots_controller.js */
const SnapshotController = {
    async displayForm() {

        const fields = { 
            'url': {}, 
            'description': {}, 
            'page': {} 
        };
        const form = document.getElementById('form');
        if (!form) return;
        
        // Clear the form and re-render only the fields
        form.innerHTML = '';
        Controller.eForm(form, fields);

        const btn = App.item('button');
        btn.type = 'button';
        btn.className = 'btn btn-outline-primary mt-2';
        btn.innerHTML = "Queue Email Task";
        form.appendChild(btn);

        btn.onclick = async (e) => {
            e.preventDefault();
            
            // Use the existing Controller utility to capture all form inputs
            // This assumes the fields match the keys in your SnapshotController.bindEmails schema
            const postData = {
                url: document.getElementById('url')?.value,
                description: document.getElementById('description')?.value,
                page: document.getElementById('page')?.value
            };

            App.spinner();

            try {
                const res = await fetch(App.url('ingestion/test'), {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(postData)
                });

                const result = await res.json();

                console.log(result);

                if (res.ok) {
                    App.flash('Success: Snapshot queued with ID ' + (result.id || 'N/A'));
                } else {
                    throw new Error(result.message || 'Server returned an error');
                }

                
            } catch (err) {
                App.flash('Error: ' + err.message);
                console.error('Snapshot POST error:', err);
            } finally {
                App.clearSpinner();
            }
        };
    },
};/** pentest_controller.js */
const PentestController = {};

PentestController.scan = async function() {
    try {
        App.spinner();
        const res = await fetch(App.url('pentest/scan/192.168.0.218'));
        const result = await res.json();

        if (res.ok) {
            App.flash('Success: scanned IP');
            this.display(result);
        } else {
            throw new Error(result.message || 'Server returned an error');
        }
    } catch (err) {
        App.flash('Error: ' + err.message);
    } finally {
        App.clearSpinner();
    }
};

PentestController.display = function(result) {
    const container = App.getItem('pentest');
    if (!container) return;

    container.innerHTML = '';

    for (let res in result) {

        
        // Bind the click event correctly
        const rowData = result[res];
        console.log(rowData);
        this.row(rowData,container);
    }
};

PentestController.row = function(rowData,container){

    for(let row in rowData){

        const tbl = App.item('table');

        tbl.setAttribute('class','tbl');

        const trOne = App.item('tr');

        const trTwo = App.item('tr');

        const trThree = App.item('tr');

        const trFour = App.item('tr');

        this.cell(rowData[row]['key'],trOne);

        this.cell(rowData[row]['value'],trOne);

        tbl.appendChild(trOne);

        this.cell('PORT',trTwo);

        this.cell(rowData[row]['port'],trTwo);

        tbl.appendChild(trTwo);

        this.cell('SERVICE',trThree);

        this.cell(rowData[row]['service'],trThree);

        tbl.appendChild(trThree);

        this.cell('RISK',trFour);

        this.cell(rowData[row]['risk'],trFour);

        tbl.appendChild(trFour);

        container.appendChild(tbl);

        console.log(rowData[row]);

    }

};

PentestController.cell = function(value,tr){

    const title = App.item('td');

    title.innerHTML = value;

    tr.appendChild(title);
};

PentestController.examine = async function(examine){

    App.flash('clicked: ' + examine);

};const PageRegistry = {
    'rag': () => RagController.bindRag(),
    'emails': () => Controller.bindEmails(),
    'agent': () => AgentController.bindAgents(),
    'docs': () => Controller.docs('docs'),
    'tiktok': () => TiktokController.bindPosts(),
    'agentemail': () => AgentController.bindAgentEmail(),
    'autoform': () => AgentController.autoForm(),
    'sales': () => SalesController.bindSales(),
    'snapshot': () => SnapshotController.displayForm(),
    'health': () => {
        HealthController.init();
        HealthController.get();
        HealthController.chat('Hello');
    },
    'pentest': () => PentestController.scan(),
    'agentic': () => AgenticController.init(),
    'mobile': () => MobileController.init()
};/**
 * Mobile Controller
 */
const MobileController = {
    init() {
        if (typeof App !== 'undefined' && App.log) {
            App.log(App);
        }
        this.getRecords();
        this.openScreen('screen-home');
    },

    // View Routing
    openScreen(screenId) {
        const screens = document.querySelectorAll('#mobile .screen');
        screens.forEach(s => s.classList.remove('active'));

        const target = document.getElementById(screenId);
        if (target) {
            target.classList.add('active');
        }
    },

    /**
     * Builds and returns a DOM element card matching #agentic markup template
     */
    cardHTML(title, category, text, ts) {
        // Main container
        const card = document.createElement('div');
        card.className = 'job-card';
        card.setAttribute('data-category', category);

        // Header Row
        const headerRow = document.createElement('div');
        headerRow.className = 'job-header-row';

        const h2 = document.createElement('h2');
        h2.textContent = title;

        const badge = document.createElement('span');
        badge.className = 'badge success';
        badge.textContent = 'Dispatched';

        headerRow.appendChild(h2);
        headerRow.appendChild(badge);

        // Subtitle / Company
        const company = document.createElement('h3');
        company.className = 'company-name';
        company.textContent = 'Sharpishly Agent ';

        const viaSpan = document.createElement('span');
        viaSpan.textContent = 'via Client Local';
        company.appendChild(viaSpan);

        // Summary Body
        const summary = document.createElement('p');
        summary.className = 'job-summary';
        summary.textContent = text;

        // Footer
        const footer = document.createElement('div');
        footer.className = 'job-footer';

        const timestamp = document.createElement('span');
        timestamp.className = 'timestamp';
        timestamp.textContent = `Created: ${ts}`;

        const btn = document.createElement('button');

        // Inside cardHTML(item):
        btn.onclick = (e) => {
            e.stopPropagation();
            this.showDetail(title, text, ts);
        };

        btn.className = 'btn btn-primary';
        btn.textContent = 'View Agent';

        footer.appendChild(timestamp);
        footer.appendChild(btn);

        // Assemble Card
        card.appendChild(headerRow);
        card.appendChild(company);
        card.appendChild(summary);
        card.appendChild(footer);

        return card;
    },

    // Convert text message -> new Agent card
    old_generateAgent() {
        const input = document.getElementById('agent-instruction');
        const text = input ? input.value.trim() : '';

        if (!text) {
            alert('Please enter an instruction message.');
            return;
        }

        // Infer category based on input context
        let title = "Sharpishly Agent";
        let category = "career";
        const lower = text.toLowerCase();

        if (lower.includes('doctor') || lower.includes('health') || lower.includes('chemist') || lower.includes('gp')) {
            title = "Doctors / Health";
            category = "health";
        } else if (lower.includes('tax') || lower.includes('council') || lower.includes('manchester')) {
            title = "Manchester City Council";
            category = "bills";
        } else if (lower.includes('bill') || lower.includes('virgin') || lower.includes('tv') || lower.includes('netflix')) {
            title = "Subscription Service";
            category = "subscription";
        }

        const ts = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

        const cardElement = this.cardHTML(title, category, text, ts);

        const agentList = document.getElementById('agentic-list');
        if (agentList) {
            agentList.prepend(cardElement);
        }

        input.value = '';
        this.openScreen('screen-agentic');
    },

    async old_1_generateAgent() {
        const input = document.getElementById('agent-instruction');
        const text = input ? input.value.trim() : '';

        if (!text) {
            alert('Please enter an instruction message.');
            return;
        }

        try {
            const response = await fetch(App.url('mobile-agent'), {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ instruction: text })
            });

            const res = await response.json();

            if (res.status === 'success' || res.data) {
                // Re-fetch server records to display persisted cards
                await this.getRecords();
                input.value = '';
                this.openScreen('screen-agentic');
            } else {
                alert(res.error || 'Failed to dispatch agent plan.');
            }
        } catch (err) {
            console.error('Error dispatching agent:', err);
        }
    },

    async generateAgent() {
        const input = document.getElementById('agent-instruction');
        const instruction = input?.value.trim();

        if (!instruction) {
            return alert('Please enter an instruction message.');
        }

        try {
            const response = await fetch(App.url('mobile-agent-create'), {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ instruction })
            });

            const res = await response.json();

            if (res.status !== 'success' && !res.data) {
                return alert(res.error || 'Failed to dispatch agent plan.');
            }

            input.value = '';
            await this.getRecords();
            this.openScreen('screen-agentic');
        } catch (err) {
            console.error('Error dispatching agent:', err);
        }
    },

    async getRecords() {
        try {
            const response = await fetch(App.url('mobile-agent'));
            const res = await response.json();

            if (res.records && Array.isArray(res.records)) {
                const agentList = document.getElementById('agentic-list');
                if (!agentList) return;

                agentList.innerHTML = '';
                res.records.forEach(item => {
                    const title = item.agent_name || item.title || 'Sharpishly Agent';
                    const category = item.role || item.category || 'career';
                    const text = item.description || item.message || item.summary || '';
                    const ts = item.created_at || '';

                    const card = this.cardHTML(title, category, text, ts);
                    agentList.appendChild(card);
                });
            }
        } catch (err) {
            console.error('Failed to fetch agent records:', err);
        }
    },

    showDetail(title, text, ts) {
            document.getElementById('detail-title').textContent = title;
            document.getElementById('detail-summary').textContent = text;
            document.getElementById('detail-timestamp').textContent = ts;

            this.openScreen('screen-agent-detail');
        },
};/** model.js */

/**
 * Model: Global App State
 */
const Model = {
    queue: [],
    healthStatus: null,
    currentPage: 'home'
};




/** view.js */
/**
 * View: Global App State
 */
const view = {
    neuralPipeline() {
        const container = document.getElementById('neural-pipeline');
        if (!container) return;

        // Clear existing content
        container.innerHTML = '';

        // Create the wrapper
        const np = App.item('div');
        np.className = 'pipeline-list';

        // Map your Model.queue to UI elements
        Model.queue.forEach(item => {
            const row = App.item('div');
            row.className = 'card mb-2 p-2 small border-0 shadow-sm';
            row.innerHTML = `
                <div class="d-flex justify-content-between">
                    <strong>${item.name}</strong>
                    <span class="text-primary">${item.status}</span>
                </div>
            `;
            np.appendChild(row);
        });

        // Append to the target
        container.appendChild(np);
    }
};


document.addEventListener('DOMContentLoaded', () => Controller.init());

/* Lightweight replacement for Bootstrap's Collapse JS */
document.addEventListener('click', (e) => {

    // Handle Navbar Toggler
    if (e.target.matches('.navbar-toggler')) {
        document.querySelector('.nav-menu').classList.toggle('show');
    }

    const toggle = e.target.closest('[data-bs-toggle="collapse"]');
    if (toggle) {
        const targetSelector = toggle.getAttribute('data-bs-target');
        const target = document.querySelector(targetSelector);
        if (target) {
            target.classList.toggle('show');
        }
    }
});
